"""The deterministic half of the report.

The agent writes the narrative; everything here is built by code from the tool-call log
and the session, so it cannot disagree with what actually ran:
  - a one-line run summary and a "key decisions" table (default vs. what the agent chose),
  - figures, each with a caption computed from the data, placed in the matching section,
  - Methods, software versions, and a disclaimer.

generate_report (tools.py) calls build_report; nothing here is exposed to the agent.
"""

from __future__ import annotations

import json
import platform
import re
from collections import defaultdict
from dataclasses import dataclass
from importlib import metadata
from pathlib import Path
from typing import Any

import numpy as np

from agent import config
from agent.session import SESSION

Entry = dict[str, Any]

DPI = 200
# Chart colours: neutral for the data, grey for the standard default, one accent for the
# agent's choice (so "what changed" reads at a glance in every figure).
DATA = "#9db4cf"
DEFAULT = "#6f6e69"
CHOSEN = "#eb6834"
BAR = "#2a78d6"
INK = "#52514e"

DISCLAIMER = (
    "*This report was produced by an AI agent ({model}). The run summary, decisions table, "
    "figures, captions and Methods are generated by code from the tool log; the narrative is "
    "written by the model and should be checked against them before use.*"
)


# --- tool log -----------------------------------------------------------------


def read_log(path: Path) -> list[Entry]:
    if not path.exists():
        return []
    return [json.loads(line) for line in path.read_text().splitlines() if line.strip()]


def _last(log: list[Entry], tool: str) -> Entry | None:
    """The last successful call to `tool`, or None."""
    for entry in reversed(log):
        if entry["tool"] == tool and "error" not in entry["summary"]:
            return entry
    return None


def _n(x) -> str:
    return f"{int(x):,}"


def _pct(part, whole) -> str:
    return f"{100 * part / whole:.1f}%" if whole else "n/a"


def _num(x) -> str:
    """Compact number: 15 -> '15', 5.0 -> '5', 0.0912 -> '0.091', 10000 -> '10,000'."""
    x = float(x)
    if x.is_integer():
        return f"{int(x):,}"
    return f"{x:.3g}"


# --- run summary and decisions table -------------------------------------------


def run_summary(log: list[Entry]) -> str:
    inspect = _last(log, "inspect_dataset")
    final = _last(log, "summarize_findings")
    if not (inspect and final):
        return ""
    s = final["summary"]
    parts = [f"**{SESSION.name}**", f"{_n(inspect['summary']['n_cells'])} → {_n(s['n_cells'])} cells"]
    if "n_clusters" in s:
        parts.append(f"{s['n_clusters']} clusters")
    if "cell_type_counts" in s:
        parts.append(f"{len(s['cell_type_counts'])} cell types")
    rep = {"X_scVI": "scVI", "X_pca": "PCA"}.get(s.get("representation"), s.get("representation"))
    if rep:
        parts.append(f"{rep} embedding")
    return " · ".join(parts)


def _choice(value: str, changed: bool) -> str:
    return f"**{value}** (changed)" if changed else f"{value} (default kept)"


def _nearest_rule(threshold: float, candidates: dict) -> str | None:
    """Name the candidate threshold the agent's choice matches (within rounding)."""
    names = {"bimodal_valley": "bimodal valley", "median_3mad": "median + 3×MAD", "scrublet_auto": "Scrublet auto"}
    for key, label in names.items():
        value = candidates.get(key)
        if value is not None and abs(value - threshold) <= max(0.005, 0.05 * value):
            return label
    return None


def decisions_table(log: list[Entry]) -> str:
    rows: list[tuple[str, str, str, str, str]] = []

    rec, filt, qc = _last(log, "recommend_qc_thresholds"), _last(log, "filter_cells_and_genes"), _last(log, "compute_qc")
    if rec and filt:
        default = rec["summary"]["recommended"]
        applied = filt["summary"]["applied"]
        impact = rec["summary"]["projected_impact"]
        showed = f"default would remove {_n(impact['cells_removed_max_pct_mt'])} of {_n(impact['cells_total'])} cells ({_pct(impact['cells_removed_max_pct_mt'], impact['cells_total'])})"
        if qc:
            showed = f"median {_num(qc['summary']['pct_counts_mt']['median'])}%; " + showed
        removed = filt["summary"]["removed"]["cells"]
        rows.append((
            "Mitochondrial cutoff",
            f"{_num(default['max_pct_mt'])}%",
            showed,
            _choice(f"{_num(applied['max_pct_mt'])}%", applied["max_pct_mt"] != default["max_pct_mt"]),
            f"{_n(removed)} cells removed by QC ({_pct(removed, filt['summary']['before']['n_cells'])})",
        ))
        floors = lambda d: f"≥{_num(d['min_genes'])} genes/cell, genes in ≥{_num(d['min_cells'])} cells"  # noqa: E731
        changed = (applied["min_genes"], applied["min_cells"]) != (default["min_genes"], default["min_cells"])
        min_seen = f"fewest genes in a cell: {_num(qc['summary']['n_genes_by_counts']['min'])}" if qc else "—"
        rows.append(("Cell and gene floors", floors(default), min_seen, _choice(floors(applied), changed),
                     f"{_n(filt['summary']['removed']['genes'])} genes removed"))

    det, dfilt = _last(log, "detect_doublets"), _last(log, "filter_doublets")
    if det and dfilt:
        d = det["summary"]
        cands = d["candidate_thresholds"]
        if cands.get("scrublet_auto_per_batch"):
            auto = " / ".join(_num(v) for v in cands["scrublet_auto_per_batch"].values() if v is not None)
            default = f"Scrublet automatic ({auto} per batch)"
        else:
            default = f"Scrublet automatic ({_num(cands['scrublet_auto'])})" if cands.get("scrublet_auto") else "Scrublet automatic"
        shape = "bimodal" if d["is_bimodal"] else "not bimodal"
        options = [f"{lbl} {_num(cands[k])}" for k, lbl in (("bimodal_valley", "valley"), ("median_3mad", "median + 3×MAD")) if cands.get(k) is not None]
        t = dfilt["args"]["threshold"]
        rule = _nearest_rule(t, cands)
        rows.append((
            "Doublet threshold",
            default,
            f"scores {shape}; " + ", ".join(options),
            f"**{_num(t)}**" + (f" ({rule})" if rule else " (custom)"),
            f"{_n(dfilt['summary']['removed'])} cells removed ({_num(dfilt['summary']['pct_removed'])}%)",
        ))

    norm = _last(log, "normalize")
    if norm:
        s = norm["summary"]
        value = f"{_num(s['target_sum'])} counts/cell, {_n(s['n_top_genes_requested'])} HVGs"
        changed = (s["target_sum"], s["n_top_genes_requested"]) != (1e4, 2000)
        hvg = f"HVGs ranked within each batch ('{s['hvg_batch_key']}')" if s.get("hvg_batch_key") else f"{_n(s['n_hvgs_flagged'])} HVGs flagged"
        rows.append(("Normalisation", "10,000 counts/cell, 2,000 HVGs", "—", _choice(value, changed), hvg))

    inspect = _last(log, "inspect_dataset")
    scvi, pca = _last(log, "run_scvi"), _last(log, "run_pca")
    dr = max((e for e in (scvi, pca) if e), key=log.index, default=None)
    if inspect and dr:
        i = inspect["summary"]
        showed = f"{i['n_batches']} batches in `obs['{i['candidate_batch_key']}']`" if i.get("candidate_batch_key") else "no batch column"
        if dr["tool"] == "run_scvi":
            s = dr["summary"]
            choice, result = "**scVI**", f"{s['n_latent']} latent dimensions, batch key '{s['batch_key']}'"
        else:
            choice, result = "PCA", f"{dr['summary']['n_comps']} components"
        rows.append(("Embedding", "PCA", showed, choice, result))

    clus = _last(log, "cluster")
    if clus:
        r = clus["summary"]["resolution"]
        rows.append(("Leiden resolution", "1.0", "—", _choice(f"{r:.1f}", r != 1.0), f"{clus['summary']['n_clusters']} clusters"))

    ann = _last(log, "annotate_celltypes")
    if ann:
        m = ann["summary"]["model"]
        rows.append(("Annotation model", "Immune_All_Low", "—", _choice(m.removesuffix(".pkl"), m != "Immune_All_Low.pkl"),
                     f"{ann['summary']['n_cell_types']} cell types"))

    if not rows:
        return ""
    lines = [
        "## Key analysis decisions",
        "",
        "Each row compares a standard default with what the agent chose after reading the data. "
        "Built from the tool log (`tool_calls.jsonl`), not written by the model.",
        "",
        "| Step | Standard default | What the data showed | Agent's choice | Effect |",
        "|---|---|---|---|---|",
    ]
    lines += ["| " + " | ".join(r) + " |" for r in rows]
    return "\n".join(lines)


# --- figures -------------------------------------------------------------------


@dataclass
class Figure:
    name: str
    alt: str
    caption: str
    # Heading patterns, tried in order, for the section this figure belongs in.
    sections: tuple[str, ...]


def _style():
    import matplotlib.pyplot as plt

    return plt.rc_context({
        "font.family": "sans-serif",
        "font.size": 10,
        "axes.spines.top": False,
        "axes.spines.right": False,
        "axes.edgecolor": INK,
        "axes.labelcolor": INK,
        "xtick.color": INK,
        "ytick.color": INK,
        "axes.titleweight": "bold",
        "axes.titlesize": 11,
        "legend.frameon": False,
    })


def _save(fig, path: Path) -> None:
    import matplotlib.pyplot as plt

    fig.savefig(path, dpi=DPI, bbox_inches="tight", facecolor="white")
    plt.close(fig)


def _cutoff(ax, x, color, label, style="-"):
    ax.axvline(x, color=color, linestyle=style, linewidth=2)
    ax.annotate(label, xy=(x, 1), xycoords=("data", "axes fraction"), xytext=(4, -4),
                textcoords="offset points", ha="left", va="top", fontsize=9, color=color, fontweight="bold")


def _qc_figure(log: list[Entry], figdir: Path) -> Figure | None:
    import matplotlib.pyplot as plt

    df = SESSION.qc_before_filter
    rec, filt = _last(log, "recommend_qc_thresholds"), _last(log, "filter_cells_and_genes")
    if df is None or not (rec and filt):
        return None
    default, applied = rec["summary"]["recommended"], filt["summary"]["applied"]
    mt, genes = df["pct_counts_mt"].to_numpy(), df["n_genes_by_counts"].to_numpy()
    n = len(df)
    lost_default = int((mt > default["max_pct_mt"]).sum())
    lost_chosen = int((mt > applied["max_pct_mt"]).sum())

    with _style():
        fig, (a1, a2) = plt.subplots(1, 2, figsize=(10, 3.4))
        a1.hist(mt, bins=60, color=DATA, edgecolor="white", linewidth=0.5)
        a1.set(xlabel="Mitochondrial reads (%)", ylabel="Cells", title="Mitochondrial fraction")
        if applied["max_pct_mt"] != default["max_pct_mt"]:
            _cutoff(a1, default["max_pct_mt"], DEFAULT, f"default {_num(default['max_pct_mt'])}%\nremoves {_pct(lost_default, n)}", "--")
        _cutoff(a1, applied["max_pct_mt"], CHOSEN, f"chosen {_num(applied['max_pct_mt'])}%\nremoves {_pct(lost_chosen, n)}")

        a2.hist(genes, bins=60, color=DATA, edgecolor="white", linewidth=0.5)
        a2.set(xlabel="Genes detected per cell", ylabel="Cells", title="Genes per cell")
        _cutoff(a2, applied["min_genes"], CHOSEN, f"floor {_num(applied['min_genes'])}")
        _save(fig, figdir / "qc_thresholds.png")

    if applied["max_pct_mt"] != default["max_pct_mt"]:
        mito = (f"The standard {_num(default['max_pct_mt'])}% mitochondrial cutoff (dashed) would remove "
                f"{_n(lost_default)} cells ({_pct(lost_default, n)}); the chosen {_num(applied['max_pct_mt'])}% cutoff "
                f"removes {_n(lost_chosen)} ({_pct(lost_chosen, n)}).")
    else:
        mito = (f"The standard {_num(default['max_pct_mt'])}% mitochondrial cutoff was kept and removes "
                f"{_n(lost_chosen)} cells ({_pct(lost_chosen, n)}).")
    caption = (f"Per-cell QC before filtering ({_n(n)} cells, median {_num(np.median(mt))}% mitochondrial). "
               f"{mito} Minimum genes per cell: {_num(applied['min_genes'])} (fewest observed: {_n(genes.min())}).")
    return Figure("qc_thresholds.png", "QC distributions with cutoffs", caption, (r"quality|\bqc\b", r"filter"))


def _doublet_figure(log: list[Entry], figdir: Path) -> Figure | None:
    import matplotlib.pyplot as plt

    scores = SESSION.doublet_scores
    det, dfilt = _last(log, "detect_doublets"), _last(log, "filter_doublets")
    if scores is None or not (det and dfilt):
        return None
    cands = det["summary"]["candidate_thresholds"]
    t = dfilt["args"]["threshold"]
    n = len(scores)
    flagged = int((scores >= t).sum())

    with _style():
        fig, ax = plt.subplots(figsize=(7, 3.4))
        ax.hist(scores, bins=80, color=DATA, edgecolor="white", linewidth=0.5)
        ax.set_yscale("log")
        ax.set(xlabel="Scrublet doublet score", ylabel="Cells (log scale)", title="Doublet scores")
        _cutoff(ax, t, CHOSEN, f"chosen {_num(t)}\nremoves {_pct(flagged, n)}")
        auto, auto_label = cands.get("scrublet_auto"), "Scrublet's automatic threshold"
        if auto is None and cands.get("scrublet_auto_per_batch"):
            vals = [v for v in cands["scrublet_auto_per_batch"].values() if v is not None]
            auto = float(np.mean(vals)) if vals else None
            auto_label = "The mean of Scrublet's per-batch automatic thresholds"
        if auto is not None and abs(auto - t) > 0.01:
            _cutoff(ax, auto, DEFAULT, f"Scrublet auto {_num(auto)}\nremoves {_pct(int((scores >= auto).sum()), n)}", "--")
        _save(fig, figdir / "doublet_scores.png")

    shape = "bimodal" if det["summary"]["is_bimodal"] else "not bimodal"
    rule = _nearest_rule(t, cands)
    caption = (f"Scrublet doublet scores for {_n(n)} cells; the distribution is {shape}. "
               f"Chosen threshold {_num(t)}" + (f" ({rule})" if rule else "") +
               f" flags {_n(flagged)} cells ({_pct(flagged, n)}).")
    if auto is not None and abs(auto - t) > 0.01:
        caption += f" {auto_label} (dashed, {_num(auto)}) would flag {_n(int((scores >= auto).sum()))}."
    return Figure("doublet_scores.png", "Doublet score distribution", caption, (r"doublet",))


def _umap_figure(adata, batch_key: str | None, figdir: Path) -> Figure | None:
    import matplotlib.pyplot as plt
    import scanpy as sc

    if "X_umap" not in adata.obsm:
        return None
    colors = [c for c in ("cell_type", "leiden") if c in adata.obs]
    # For multi-batch data, colouring by batch shows whether integration mixed the batches
    # (good) or left them as separate islands (not integrated).
    if batch_key and batch_key in adata.obs:
        colors.append(batch_key)
    titles = {"cell_type": "Cell type", "leiden": "Leiden cluster", batch_key: "Batch"}
    with _style():
        sc.pl.umap(adata, color=colors, title=[titles[c] for c in colors], show=False, wspace=0.45,
                   frameon=False, legend_fontsize=8)
        _save(plt.gcf(), figdir / "umap.png")
    rep = {"X_scVI": "the scVI latent space", "X_pca": "PCA"}.get(SESSION.representation, SESSION.representation)
    names = [titles[c] if c == "leiden" else titles[c].lower() for c in colors]
    by = names[0] if len(names) == 1 else ", ".join(names[:-1]) + " and " + names[-1]
    caption = f"UMAP of {_n(adata.n_obs)} cells computed on {rep}, coloured by {by}."
    if batch_key in colors:
        caption += " Batches that overlap within each cell type indicate the integration worked."
    return Figure("umap.png", "UMAP", caption, (r"cluster", r"dimension|embedding|integration|umap"))


def _composition_figure(adata, figdir: Path) -> Figure | None:
    import matplotlib.pyplot as plt

    if "cell_type" not in adata.obs:
        return None
    counts = adata.obs["cell_type"].value_counts().sort_values()
    total = int(counts.sum())
    with _style():
        fig, ax = plt.subplots(figsize=(7, 0.32 * len(counts) + 0.9))
        ax.barh(counts.index.astype(str), counts.values, color=BAR, height=0.7)
        for y, v in enumerate(counts.values):
            ax.annotate(f"{_n(v)} ({_pct(v, total)})", xy=(v, y), xytext=(4, 0), textcoords="offset points",
                        va="center", fontsize=8, color=INK)
        ax.set(xlabel="Cells", title="Cell-type composition")
        ax.spines["left"].set_visible(False)
        ax.tick_params(axis="y", length=0)
        ax.set_xlim(0, counts.max() * 1.22)
        _save(fig, figdir / "composition.png")
    caption = (f"Cells per annotated type ({_n(total)} cells, {len(counts)} types; CellTypist majority vote "
               "over Leiden clusters).")
    return Figure("composition.png", "Cell-type composition", caption, (r"composition", r"annot|cell.type"))


def _dotplot_figure(adata, groupby: str, figdir: Path) -> Figure | None:
    import matplotlib.pyplot as plt
    import scanpy as sc

    if groupby not in adata.obs or adata.obs[groupby].nunique() < 2:
        return None
    # Dedicated key so the cluster markers from identify_markers stay intact.
    key = f"dea_{groupby}"
    sc.tl.rank_genes_groups(adata, groupby, method="wilcoxon", key_added=key)
    what = "Leiden cluster" if groupby == "leiden" else "cell type"
    name = "marker_dotplot_clusters.png" if groupby == "leiden" else "marker_dotplot_celltype.png"
    with _style():
        sc.pl.rank_genes_groups_dotplot(adata, n_genes=5, key=key, groupby=groupby, standard_scale="var", show=False)
        _save(plt.gcf(), figdir / name)
    caption = (f"Top 5 marker genes per {what} (Wilcoxon rank-sum). Dot size: fraction of cells expressing; "
               "colour: mean expression scaled per gene.")
    return Figure(name, f"Marker genes per {what}", caption, (r"marker", r"annot|cell.type"))


def draw_figures(adata, log: list[Entry], batch_key: str | None, figdir: Path) -> list[Figure]:
    import matplotlib

    matplotlib.use("Agg")
    figdir.mkdir(parents=True, exist_ok=True)
    figures = [
        _qc_figure(log, figdir),
        _doublet_figure(log, figdir),
        _umap_figure(adata, batch_key, figdir),
        _dotplot_figure(adata, "leiden", figdir),
        _composition_figure(adata, figdir),
        _dotplot_figure(adata, "cell_type", figdir),
    ]
    return [f for f in figures if f]


def _figure_md(fig: Figure) -> str:
    return f"![{fig.alt}](figures/{fig.name})\n\n*{fig.caption}*"


_HEADING = re.compile(r"^(#{1,6})\s+(.*)$")


def place_figures(markdown: str, figures: list[Figure]) -> tuple[str, list[Figure]]:
    """Insert each figure at the end of the first section whose heading matches one of its
    patterns. Returns the new markdown and the figures no section matched."""
    lines = markdown.splitlines()
    headings = [(i, len(m.group(1)), m.group(2)) for i, line in enumerate(lines) if (m := _HEADING.match(line))]
    inserts: dict[int, list[Figure]] = defaultdict(list)
    unplaced = []
    for fig in figures:
        target = None
        for pattern in fig.sections:
            for k, (_, level, text) in enumerate(headings):
                if level > 1 and re.search(pattern, text, re.IGNORECASE):
                    target = next((j for j, lv, _ in headings[k + 1 :] if lv <= level), len(lines))
                    break
            if target is not None:
                break
        if target is None:
            unplaced.append(fig)
        else:
            inserts[target].append(fig)

    out: list[str] = []
    for i in range(len(lines) + 1):
        for fig in inserts.get(i, []):
            while out and not out[-1].strip():
                out.pop()
            out += ["", _figure_md(fig), ""]
        if i < len(lines):
            out.append(lines[i])
    return "\n".join(out), unplaced


def _insert_after_intro(markdown: str, block: str, skip_overview: bool = True) -> str:
    """Put `block` straight after the title, or after the opening overview section."""
    lines = markdown.strip("\n").splitlines()
    headings = [(i, len(m.group(1)), m.group(2)) for i, line in enumerate(lines) if (m := _HEADING.match(line))]
    at = 0
    if headings and headings[0][1] == 1:
        at = headings[0][0] + 1
        rest = headings[1:]
        if skip_overview and rest and re.search(r"overview|summary|introduction", rest[0][2], re.IGNORECASE):
            at = next((i for i, lv, _ in rest[1:] if lv <= rest[0][1]), len(lines))
    return "\n".join(lines[:at] + ["", block, ""] + lines[at:])


# --- methods -------------------------------------------------------------------


def methods(log: list[Entry]) -> str:
    paras = []
    ids = _last(log, "check_gene_identifiers")
    qc = _last(log, "compute_qc")
    if ids and qc:
        paras.append(
            f"**Quality control.** Per-cell metrics were computed with scanpy `calculate_qc_metrics`; "
            f"mitochondrial genes were those prefixed `{ids['summary']['mito_prefix']}` "
            f"({qc['summary']['n_mito_genes_found']} found)."
        )
    filt = _last(log, "filter_cells_and_genes")
    if filt:
        a, s = filt["summary"]["applied"], filt["summary"]
        paras.append(
            f"**Filtering.** Cells with fewer than {_num(a['min_genes'])} detected genes or more than "
            f"{_num(a['max_pct_mt'])}% mitochondrial reads were removed, as were genes detected in fewer than "
            f"{_num(a['min_cells'])} cells ({_n(s['before']['n_cells'])} → {_n(s['after']['n_cells'])} cells, "
            f"{_n(s['before']['n_genes'])} → {_n(s['after']['n_genes'])} genes)."
        )
    det, dfilt = _last(log, "detect_doublets"), _last(log, "filter_doublets")
    if det and dfilt:
        per = f", run separately within each batch ('{det['summary']['batch_key']}')," if det["summary"]["batch_key"] else ""
        paras.append(
            f"**Doublets.** Doublet scores were computed with Scrublet (scanpy `pp.scrublet`){per} on raw counts; "
            f"cells scoring ≥ {_num(dfilt['args']['threshold'])} were removed "
            f"({_n(dfilt['summary']['removed'])} cells, {_num(dfilt['summary']['pct_removed'])}%)."
        )
    norm = _last(log, "normalize")
    if norm:
        s = norm["summary"]
        within = f", ranked within each batch ('{s['hvg_batch_key']}')" if s.get("hvg_batch_key") else ""
        paras.append(
            f"**Normalisation.** Raw counts were kept in `layers['counts']`; expression was scaled to "
            f"{_num(s['target_sum'])} counts per cell and log1p-transformed. The top {_n(s['n_top_genes_requested'])} "
            f"highly variable genes were flagged{within}."
        )
    scvi, pca = _last(log, "run_scvi"), _last(log, "run_pca")
    dr = max((e for e in (scvi, pca) if e), key=log.index, default=None)
    if dr and dr["tool"] == "run_scvi":
        s = dr["summary"]
        paras.append(
            f"**Embedding.** An scVI model ({s['n_latent']} latent dimensions, {s['epochs_trained']} epochs) was "
            f"trained on raw counts of {_n(s['n_hvgs_used'])} highly variable genes with batch key "
            f"'{s['batch_key']}'; its latent space was used downstream."
        )
    elif dr:
        paras.append(f"**Embedding.** PCA ({dr['summary']['n_comps']} components) on the highly variable genes.")
    clus = _last(log, "cluster")
    if clus:
        paras.append(
            f"**Clustering.** A k-nearest-neighbour graph on that embedding was clustered with Leiden "
            f"(resolution {clus['summary']['resolution']:.1f}; {clus['summary']['n_clusters']} clusters) and "
            f"embedded with UMAP."
        )
    mk, ann = _last(log, "identify_markers"), _last(log, "annotate_celltypes")
    if mk or ann:
        text = "**Markers and annotation.** "
        if mk:
            text += "Marker genes per cluster were ranked with a Wilcoxon rank-sum test. "
        if ann:
            text += (f"Cell types were assigned with CellTypist (model `{ann['summary']['model']}`), using majority "
                     "voting over the Leiden clusters.")
        paras.append(text.strip())
    if not paras:
        return ""

    packages = ["scanpy", "anndata", "numpy", "scipy"]
    if scvi:
        packages.append("scvi-tools")
    if ann:
        packages.append("celltypist")
    rows = [("Python", platform.python_version())] + [(p, _version(p)) for p in packages]
    rows.append(("LLM (analysis decisions and narrative)", config.MODEL))
    software = "\n".join(["| Software | Version |", "|---|---|"] + [f"| {a} | {b} |" for a, b in rows])

    return "\n\n".join([
        "## Methods",
        "*Generated from the tool log: these are the steps and parameters that actually ran.*",
        *paras,
        "### Software",
        software,
        "### Reproducibility",
        f"Random seed {config.SEED} for all stochastic steps. Every tool call, with the arguments the agent "
        "chose and the summary it read back, is in `tool_calls.jsonl`. The agent's choices are sampled from the "
        "model, so a re-run can take different decisions.",
    ])


def _version(package: str) -> str:
    try:
        return metadata.version(package)
    except metadata.PackageNotFoundError:
        return "unknown"


# --- facts and tables the narrative cites (placeholders) ----------------------
#
# The agent never types a number into the report. It writes {{name}} for a fact below,
# {{celltype:NAME}} for one cell type's size, {{celltypes:A|B}} for several combined, and
# {{table:name}} for a code-built table; render() fills them in and rejects the report if
# any other number appears.

_QC_METRICS = {"genes": "n_genes_by_counts", "counts": "total_counts", "mito": "pct_counts_mt"}
_MARKERS_SHOWN = 5


def _p(value) -> str:
    return f"{_num(value)}%"


def facts(log: list[Entry], adata) -> dict[str, str]:
    f: dict[str, str] = {}
    if e := _last(log, "inspect_dataset"):
        s = e["summary"]
        f["input.n_cells"], f["input.n_genes"] = _n(s["n_cells"]), _n(s["n_genes"])
        if s.get("candidate_batch_key"):
            f["input.n_batches"], f["input.batch_key"] = str(s["n_batches"]), s["candidate_batch_key"]
    if e := _last(log, "compute_qc"):
        s = e["summary"]
        f["qc.n_mito_genes"] = str(s["n_mito_genes_found"])
        for short, col in _QC_METRICS.items():
            for q, v in s[col].items():
                f[f"qc.{short}.{q}"] = _p(v) if short == "mito" else _n(round(v))
    if e := _last(log, "recommend_qc_thresholds"):
        d, imp = e["summary"]["recommended"], e["summary"]["projected_impact"]
        f["default.max_pct_mt"], f["default.min_genes"], f["default.min_cells"] = _p(d["max_pct_mt"]), _n(d["min_genes"]), _n(d["min_cells"])
        f["default.mito_cells_removed"] = _n(imp["cells_removed_max_pct_mt"])
        f["default.mito_pct_removed"] = _pct(imp["cells_removed_max_pct_mt"], imp["cells_total"])
    if e := _last(log, "filter_cells_and_genes"):
        s = e["summary"]
        a = s["applied"]
        f["filter.max_pct_mt"], f["filter.min_genes"], f["filter.min_cells"] = _p(a["max_pct_mt"]), _n(a["min_genes"]), _n(a["min_cells"])
        f["filter.cells_before"], f["filter.cells_after"] = _n(s["before"]["n_cells"]), _n(s["after"]["n_cells"])
        f["filter.cells_removed"] = _n(s["removed"]["cells"])
        f["filter.pct_cells_removed"] = _pct(s["removed"]["cells"], s["before"]["n_cells"])
        f["filter.genes_before"], f["filter.genes_after"] = _n(s["before"]["n_genes"]), _n(s["after"]["n_genes"])
        f["filter.genes_removed"] = _n(s["removed"]["genes"])
    if e := _last(log, "detect_doublets"):
        s = e["summary"]
        c = s["candidate_thresholds"]
        f["doublet.distribution"] = "bimodal" if s["is_bimodal"] else "not bimodal"
        f["doublet.score_median"], f["doublet.score_max"] = _num(s["score_distribution"]["median"]), _num(s["score_distribution"]["max"])
        f["doublet.median_3mad"] = _num(c["median_3mad"])
        if c.get("bimodal_valley") is not None:
            f["doublet.valley"] = _num(c["bimodal_valley"])
        autos = [c["scrublet_auto"]] if c.get("scrublet_auto") is not None else [
            v for v in (c.get("scrublet_auto_per_batch") or {}).values() if v is not None]
        if autos:
            f["doublet.scrublet_auto"] = " / ".join(_num(v) for v in autos)
            if SESSION.doublet_scores is not None:
                flagged = int((SESSION.doublet_scores >= float(np.mean(autos))).sum())
                f["doublet.scrublet_auto_cells_flagged"] = _n(flagged)
    if e := _last(log, "filter_doublets"):
        s = e["summary"]
        f["doublet.threshold"] = _num(s["threshold"])
        if det := _last(log, "detect_doublets"):
            f["doublet.rule"] = _nearest_rule(s["threshold"], det["summary"]["candidate_thresholds"]) or "custom threshold"
        f["doublet.cells_before"], f["doublet.cells_after"] = _n(s["before_cells"]), _n(s["after_cells"])
        f["doublet.cells_removed"], f["doublet.pct_removed"] = _n(s["removed"]), _p(s["pct_removed"])
    if e := _last(log, "normalize"):
        s = e["summary"]
        f["norm.target_sum"], f["norm.n_hvgs"] = _num(s["target_sum"]), _n(s["n_hvgs_flagged"])
    if e := _last(log, "run_pca"):
        s = e["summary"]
        f["pca.n_comps"] = str(s["n_comps"])
        for k, v in enumerate(s["variance_ratio_top10"][:3], start=1):
            f[f"pca.pc{k}_variance"] = _p(round(100 * v, 1))
    if e := _last(log, "run_scvi"):
        s = e["summary"]
        f["scvi.n_latent"], f["scvi.n_hvgs"] = str(s["n_latent"]), _n(s["n_hvgs_used"])
        if s.get("epochs_trained"):
            f["scvi.epochs"] = str(s["epochs_trained"])
    if e := _last(log, "cluster"):
        s = e["summary"]
        sizes = s["cluster_sizes"].values()
        f["cluster.resolution"], f["cluster.n"] = f"{s['resolution']:.1f}", str(s["n_clusters"])
        f["cluster.smallest"], f["cluster.largest"] = _n(min(sizes)), _n(max(sizes))
    f["markers.n_shown"] = str(_MARKERS_SHOWN)
    if "cell_type" in adata.obs:
        f["celltype.n"] = str(adata.obs["cell_type"].nunique())
    if e := _last(log, "inspect_dataset"):
        total = e["summary"]["n_cells"]
        f["final.n_cells"], f["final.n_genes"] = _n(adata.n_obs), _n(adata.n_vars)
        f["final.cells_removed"] = _n(total - adata.n_obs)
        f["final.pct_removed"] = _pct(total - adata.n_obs, total)
    return f


def _celltypes(adata, names: list[str]) -> str | None:
    if "cell_type" not in adata.obs:
        return None
    counts = adata.obs["cell_type"].value_counts()
    if any(n not in counts.index for n in names):
        return None
    k = int(counts[names].sum())
    return f"{_n(k)} cells ({_pct(k, adata.n_obs)})"


def tables(log: list[Entry], adata) -> dict[str, str]:
    out: dict[str, str] = {}
    obs = adata.obs
    if "leiden" in obs and "cell_type" in obs:
        names = adata.uns["rank_genes_groups"]["names"] if "rank_genes_groups" in adata.uns else None
        majority = obs.groupby("leiden", observed=True)["cell_type"].agg(lambda s: s.value_counts().index[0])
        sizes = obs["leiden"].value_counts()
        rows = ["| Cluster | Cells | Top marker genes | Cell type (majority vote) |", "|---|---|---|---|"]
        for cl in sorted(majority.index, key=lambda c: int(c) if str(c).isdigit() else str(c)):
            markers = ", ".join(str(names[str(cl)][i]) for i in range(_MARKERS_SHOWN)) if names is not None else "—"
            rows.append(f"| {cl} | {_n(sizes[cl])} | {markers} | {majority[cl]} |")
        out["clusters"] = "\n".join(rows)
    if "cell_type" in obs:
        counts = obs["cell_type"].value_counts()
        rows = ["| Cell type | Cells | Share |", "|---|---|---|"]
        rows += [f"| {name} | {_n(v)} | {_pct(v, adata.n_obs)} |" for name, v in counts.items()]
        rows.append(f"| **Total** | **{_n(adata.n_obs)}** | |")
        out["composition"] = "\n".join(rows)
    steps = []
    if e := _last(log, "inspect_dataset"):
        steps.append(("Input", e["summary"]["n_cells"], e["summary"]["n_genes"]))
    if e := _last(log, "filter_cells_and_genes"):
        s = e["summary"]
        steps.append((f"After QC filters (≤{_p(s['applied']['max_pct_mt'])} mito, ≥{_n(s['applied']['min_genes'])} genes/cell)",
                      s["after"]["n_cells"], s["after"]["n_genes"]))
    if e := _last(log, "filter_doublets"):
        steps.append((f"After doublet removal (score < {_num(e['summary']['threshold'])})", e["summary"]["after_cells"], None))
    if steps:
        rows = ["| Step | Cells | Genes |", "|---|---|---|"]
        genes = None
        for name, cells, g in steps:
            genes = g if g is not None else genes
            rows.append(f"| {name} | {_n(cells)} | {_n(genes) if genes is not None else '—'} |")
        out["steps"] = "\n".join(rows)
    return out


REQUIRED_TABLES = ("clusters", "composition")
_PLACEHOLDER = re.compile(r"\{\{\s*([^{}]+?)\s*\}\}")
# A number standing on its own: not part of a gene or dataset name (CD14, MT-CO1, PBMC3k,
# PC1, 10x). Percent signs and thousands separators are included in the match.
_BARE_NUMBER = re.compile(r"(?<![\w\-.,+])\d+(?:[.,]\d+)*(?:\s?%)?(?![\w])")
_CLUSTER_REF = re.compile(r"\bclusters?\s+(\d+(?:\s*(?:,|and|or|&|/)\s*\d+)*)", re.IGNORECASE)
# Allowed forms that contain digits but are names, not values: the "median + 3×MAD" rule
# and gene shorthand such as S100A8/9 (S100A8 and S100A9).
_ALLOWED = re.compile(r"\b3\s*[×x*]\s*MAD\b|(?<=[A-Za-z])(\d+)(?:/\d+)+\b")
_LINE_PREFIX = re.compile(r"^\s*(?:#{1,6}\s+\d+(?:\.\d+)*\.?|\d+\.)\s")  # "## 2. QC", "1. item"


def _stray_numbers(markdown: str, cluster_ids: set[str]) -> tuple[list[str], list[str]]:
    """Numbers the model typed itself, and cluster references to clusters that don't exist."""
    stray, bad_clusters = [], []
    for line in markdown.splitlines():
        if line.lstrip().startswith("!["):
            continue
        text = _LINE_PREFIX.sub(" ", line)
        text = _PLACEHOLDER.sub(" ", text)
        text = _ALLOWED.sub(lambda m: m.group(1) or " ", text)

        def _cluster(m: re.Match) -> str:
            for cid in re.findall(r"\d+", m.group(1)):
                if cid not in cluster_ids:
                    bad_clusters.append(f"cluster {cid} does not exist (clusters: {', '.join(sorted(cluster_ids, key=int))})")
            return " "

        text = _CLUSTER_REF.sub(_cluster, text) if cluster_ids else text
        for m in _BARE_NUMBER.finditer(text):
            context = text[max(0, m.start() - 30) : m.end() + 15].strip()
            stray.append(f"'{m.group(0)}' in \"...{context}...\"")
    return list(dict.fromkeys(stray)), list(dict.fromkeys(bad_clusters))


def render(markdown: str, log: list[Entry], adata) -> tuple[str, list[str]]:
    """Fill every placeholder and check the narrative. Returns the rendered text and every
    problem found (empty if the report is clean)."""
    known, tabs = facts(log, adata), tables(log, adata)
    cluster_ids = set(adata.obs["leiden"].astype(str)) if "leiden" in adata.obs else set()
    problems: list[str] = []

    for m in re.finditer(r"^#{1,6}\s+(.*)$", markdown, re.MULTILINE):
        if re.search(r"\bmethods?\b", m.group(1), re.IGNORECASE):
            problems.append(f"remove the '{m.group(1).strip()}' section: Methods is generated from the tool log "
                            "and appended automatically. Explain analysis choices in the relevant results section.")

    stray, bad_clusters = _stray_numbers(markdown, cluster_ids)
    problems += [f"number typed directly, use a placeholder: {s}" for s in stray]
    problems += bad_clusters

    placed: set[str] = set()

    def _fill(m: re.Match) -> str:
        key = m.group(1)
        kind, _, arg = key.partition(":")
        value = None
        if kind == "table" and arg in tabs:
            placed.add(arg)
            return f"\n\n{tabs[arg]}\n\n"
        if not arg:
            value = known.get(key)
        elif kind == "celltype":
            value = _celltypes(adata, [arg.strip()])
        elif kind == "celltypes":
            value = _celltypes(adata, [a.strip() for a in arg.split("|")])
        if value is None:
            problems.append(f"unknown placeholder {{{{{key}}}}}")
            return f"⚠[unknown: {key}]"
        return value

    text = _PLACEHOLDER.sub(_fill, markdown)
    # "{{celltype:X}} cells" would read "12 cells (3.0%) cells".
    text = re.sub(r"(\d cells \([\d.]+%\))\s+cells\b", r"\1", text)
    problems += [f"required table not placed: {{{{table:{t}}}}}" for t in REQUIRED_TABLES if t in tabs and t not in placed]
    return text, problems


# --- assembly ------------------------------------------------------------------


def build_report(adata, narrative: str, batch_key: str | None, warnings: list[str] = ()) -> tuple[str, list[Figure]]:
    """Assemble the final report from the rendered narrative and the code-built parts.
    `warnings` are checks the narrative still fails; they are shown at the top."""
    log = read_log(SESSION.paths.tool_log)
    figures = draw_figures(adata, log, batch_key, SESSION.paths.figures)

    narrative = narrative.strip()
    if not narrative.startswith("# "):
        narrative = f"# Single-cell RNA-seq analysis: {SESSION.name}\n\n{narrative}"
    body, unplaced = place_figures(narrative, figures)
    if warnings:
        note = "> **⚠ This report failed automatic checks and needs review:**\n" + "\n".join(f"> - {w}" for w in warnings)
        body = _insert_after_intro(body, note, skip_overview=False)
    if table := decisions_table(log):
        body = _insert_after_intro(body, table)
    if summary := run_summary(log):
        body = _insert_after_intro(body, summary, skip_overview=False)
    parts = [body]
    if unplaced:
        parts.append("## Figures\n\n" + "\n\n".join(_figure_md(f) for f in unplaced))
    parts += [methods(log), "---", DISCLAIMER.format(model=config.MODEL)]
    text = "\n\n".join(p for p in parts if p)
    return re.sub(r"\n{3,}", "\n\n", text).rstrip() + "\n", figures
