"""The deterministic half of the report.

The agent writes the narrative; everything here is built by code from the tool-call log
and the session, so it cannot disagree with what actually ran:
  - a one-line run summary and a "key decisions" table (default vs. what the agent chose),
  - figures, each with a caption computed from the data, placed in the matching section,
  - Methods, software versions, and a disclaimer.

generate_report (tools.py) calls build_report; nothing here is exposed to the agent.
"""

from __future__ import annotations

import json
import platform
import re
from collections import defaultdict
from dataclasses import dataclass
from importlib import metadata
from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd

from agent import config
from agent.session import SESSION

Entry = dict[str, Any]

DPI = 200
# Chart colours: neutral for the data, grey for the standard default, one accent for the
# agent's choice (so "what changed" reads at a glance in every figure).
DATA = "#9db4cf"
DEFAULT = "#6f6e69"
CHOSEN = "#eb6834"
BAR = "#2a78d6"
INK = "#52514e"

DISCLAIMER = (
    "*This report was produced by an AI agent ({model}). The run summary, decisions table, "
    "figures, captions and Methods are generated by code from the tool log; the narrative is "
    "written by the model and should be checked against them before use.*"
)


# --- tool log -----------------------------------------------------------------


def read_log(path: Path) -> list[Entry]:
    if not path.exists():
        return []
    return [json.loads(line) for line in path.read_text().splitlines() if line.strip()]


def _last(log: list[Entry], tool: str) -> Entry | None:
    """The last successful call to `tool`, or None."""
    for entry in reversed(log):
        if entry["tool"] == tool and "error" not in entry["summary"]:
            return entry
    return None


def _n(x) -> str:
    return f"{int(x):,}"


def _pct(part, whole) -> str:
    return f"{100 * part / whole:.1f}%" if whole else "n/a"


def _num(x) -> str:
    """Compact number: 15 -> '15', 5.0 -> '5', 0.0912 -> '0.091', 10000 -> '10,000'."""
    x = float(x)
    if x.is_integer():
        return f"{int(x):,}"
    return f"{x:.3g}"


# --- run summary and decisions table -------------------------------------------


def run_summary(log: list[Entry]) -> str:
    inspect = _last(log, "inspect_dataset")
    final = _last(log, "summarize_findings")
    if not (inspect and final):
        return ""
    s = final["summary"]
    parts = [f"**{SESSION.name}**", f"{_n(inspect['summary']['n_cells'])} → {_n(s['n_cells'])} cells"]
    if "n_clusters" in s:
        parts.append(f"{s['n_clusters']} clusters")
    if "cell_type_counts" in s:
        parts.append(f"{len(s['cell_type_counts'])} cell types")
    rep = {"X_scVI": "scVI", "X_pca": "PCA"}.get(s.get("representation"), s.get("representation"))
    if rep:
        parts.append(f"{rep} embedding")
    return " · ".join(parts)


def _choice(value: str, changed: bool) -> str:
    return f"**{value}** (changed)" if changed else f"{value} (default kept)"


def _nearest_rule(threshold: float, candidates: dict) -> str | None:
    """Name the candidate threshold the agent's choice matches (within rounding)."""
    names = {"bimodal_valley": "bimodal valley", "median_3mad": "median + 3×MAD", "scrublet_auto": "Scrublet auto"}
    options = [(label, candidates.get(key)) for key, label in names.items()]
    # With per-run Scrublet, each run has its own automatic threshold.
    options += [(f"Scrublet auto, {batch} run", v) for batch, v in (candidates.get("scrublet_auto_per_batch") or {}).items()]
    for label, value in options:
        if value is not None and abs(value - threshold) <= max(0.005, 0.05 * value):
            return label
    return None


def decisions_table(log: list[Entry]) -> str:
    rows: list[tuple[str, str, str, str, str]] = []

    rec, filt, qc = _last(log, "recommend_qc_thresholds"), _last(log, "filter_cells_and_genes"), _last(log, "compute_qc")
    if rec and filt:
        default = rec["summary"]["recommended"]
        applied = filt["summary"]["applied"]
        impact = rec["summary"]["projected_impact"]
        showed = f"default would remove {_n(impact['cells_removed_max_pct_mt'])} of {_n(impact['cells_total'])} cells ({_pct(impact['cells_removed_max_pct_mt'], impact['cells_total'])})"
        if qc:
            showed = f"median {_num(qc['summary']['pct_counts_mt']['median'])}%; " + showed
        removed = filt["summary"]["removed"]["cells"]
        rows.append((
            "Mitochondrial cutoff",
            f"{_num(default['max_pct_mt'])}%",
            showed,
            _choice(f"{_num(applied['max_pct_mt'])}%", applied["max_pct_mt"] != default["max_pct_mt"]),
            f"{_n(removed)} cells removed by QC ({_pct(removed, filt['summary']['before']['n_cells'])})",
        ))
        floors = lambda d: f"≥{_num(d['min_genes'])} genes/cell, genes in ≥{_num(d['min_cells'])} cells"  # noqa: E731
        changed = (applied["min_genes"], applied["min_cells"]) != (default["min_genes"], default["min_cells"])
        min_seen = f"fewest genes in a cell: {_num(qc['summary']['n_genes_by_counts']['min'])}" if qc else "—"
        rows.append(("Cell and gene floors", floors(default), min_seen, _choice(floors(applied), changed),
                     f"{_n(filt['summary']['removed']['genes'])} genes removed"))

    det, dfilt = _last(log, "detect_doublets"), _last(log, "filter_doublets")
    if det and dfilt:
        d = det["summary"]
        cands = d["candidate_thresholds"]
        if cands.get("scrublet_auto_per_batch"):
            auto = " / ".join(_num(v) for v in cands["scrublet_auto_per_batch"].values() if v is not None)
            default = f"Scrublet automatic ({auto} per batch)"
        else:
            default = f"Scrublet automatic ({_num(cands['scrublet_auto'])})" if cands.get("scrublet_auto") else "Scrublet automatic"
        shape = "bimodal" if d["is_bimodal"] else "not bimodal"
        options = [f"{lbl} {_num(cands[k])}" for k, lbl in (("bimodal_valley", "valley"), ("median_3mad", "median + 3×MAD")) if cands.get(k) is not None]
        t = dfilt["args"]["threshold"]
        rule = _nearest_rule(t, cands)
        rows.append((
            "Doublet threshold",
            default,
            f"scores {shape}; " + ", ".join(options),
            f"**{_num(t)}**" + (f" ({rule})" if rule else " (custom)"),
            f"{_n(dfilt['summary']['removed'])} cells removed ({_num(dfilt['summary']['pct_removed'])}%)",
        ))
    elif det:
        rows.append(("Doublet threshold", "Scrublet automatic", "scores computed", "**skipped** (no filter)", "0 cells removed"))
    else:
        rows.append(("Doublet threshold", "Scrublet automatic", "—", "**skipped** (not run)", "0 cells removed"))

    norm = _last(log, "normalize")
    if norm:
        s = norm["summary"]
        value = f"{_num(s['target_sum'])} counts/cell, {_n(s['n_top_genes_requested'])} HVGs"
        changed = (s["target_sum"], s["n_top_genes_requested"]) != (1e4, 2000)
        hvg = f"HVGs ranked within each batch ('{s['hvg_batch_key']}')" if s.get("hvg_batch_key") else f"{_n(s['n_hvgs_flagged'])} HVGs flagged"
        rows.append(("Normalisation", "10,000 counts/cell, 2,000 HVGs", "—", _choice(value, changed), hvg))

    inspect = _last(log, "inspect_dataset")
    scvi, pca = _last(log, "run_scvi"), _last(log, "run_pca")
    dr = max((e for e in (scvi, pca) if e), key=log.index, default=None)
    if inspect and dr:
        i = inspect["summary"]
        showed = f"{i['n_batches']} batches in `obs['{i['candidate_batch_key']}']`" if i.get("candidate_batch_key") else "no batch column"
        if dr["tool"] == "run_scvi":
            s = dr["summary"]
            cols = s.get("batch_columns") or ([s["batch_key"]] if s["batch_key"] else [])
            choice = f"**scVI**, correcting for {' × '.join(cols)}" if cols else "**scVI**, no batch correction"
            result = f"{s['n_latent']} latent dimensions, {s.get('n_batches', '?')} batches"
        else:
            choice, result = "PCA", f"{dr['summary']['n_comps']} components"
        rows.append(("Embedding", "PCA", showed, choice, result))

    clus = _last(log, "cluster")
    if clus:
        r = clus["summary"]["resolution"]
        rows.append(("Leiden resolution", "1.0", "—", _choice(f"{r:.1f}", r != 1.0), f"{clus['summary']['n_clusters']} clusters"))

    ann = _last(log, "annotate_celltypes")
    if ann:
        m = ann["summary"]["model"]
        rows.append(("Annotation model", "Immune_All_Low", "—", _choice(m.removesuffix(".pkl"), m != "Immune_All_Low.pkl"),
                     f"{ann['summary']['n_cell_types']} cell types"))

    for e in log:
        if e["tool"] == "relabel_clusters" and "error" not in e["summary"]:
            changes = e["summary"]["changes"]
            what = "; ".join(f"cluster {c['cluster']}: {c['from']} → **{c['to']}**" for c in changes)
            n = sum(c["n_cells"] for c in changes)
            rows.append(("Cluster labels", "CellTypist majority vote", e["args"]["reason"], what, f"{_n(n)} cells relabelled"))

    comp = _last(log, "compare_composition")
    if comp:
        a, sm = comp["args"], comp["summary"]
        rows.append(("Composition test", "—", f"{' / '.join(f'{v} {k}' for k, v in sm['n_samples'].items())} samples",
                     f"{'paired ' if sm['paired'] else ''}{sm['test']} by '{a['sample_key']}'",
                     f"{sm['n_significant']} of {len(sm['results'])} cell types changed (padj < 0.05)"))
    de = _last(log, "run_pseudobulk_de")
    if de:
        a, sm = de["args"], de["summary"]
        factor = a["contrast"][0]
        paired = a["sample_key"] in (a.get("covariates") or [])
        n_deg = sum(r["n_significant"] for r in sm["results"].values())
        rows.append(("DE design", f"~ {factor}", f"replicates in '{a['sample_key']}'",
                     f"**{sm['design'].replace('~', '~ ')}**" + (" (paired)" if paired else ""),
                     f"{len(sm['results'])} cell types tested, {_n(n_deg)} significant genes in total"))
        mc = a.get("min_cells", 10)
        rows.append(("Min cells per pseudobulk sample", "10", "—", _choice(str(mc), mc != 10),
                     f"{len(sm['skipped'])} cell types skipped" if sm["skipped"] else "no cell types skipped"))

    if not rows:
        return ""
    lines = [
        "## Key analysis decisions",
        "",
        "Each row compares a standard default with what the agent chose after reading the data. "
        "Built from the tool log (`tool_calls.jsonl`), not written by the model"
        + (", except the relabelling reasons, which quote the agent's tool call." if any(r[0] == "Cluster labels" for r in rows) else "."),
        "",
        "| Step | Standard default | What the data showed | Agent's choice | Effect |",
        "|---|---|---|---|---|",
    ]
    lines += ["| " + " | ".join(r) + " |" for r in rows]
    return "\n".join(lines)


# --- figures -------------------------------------------------------------------


@dataclass
class Figure:
    name: str
    alt: str
    caption: str
    # Heading patterns, tried in order, for the section this figure belongs in.
    sections: tuple[str, ...]


def _style():
    import matplotlib.pyplot as plt

    return plt.rc_context({
        "font.family": "sans-serif",
        "font.size": 10,
        "axes.spines.top": False,
        "axes.spines.right": False,
        "axes.edgecolor": INK,
        "axes.labelcolor": INK,
        "xtick.color": INK,
        "ytick.color": INK,
        "axes.titleweight": "bold",
        "axes.titlesize": 11,
        "legend.frameon": False,
    })


def _save(fig, path: Path) -> None:
    import matplotlib.pyplot as plt

    fig.savefig(path, dpi=DPI, bbox_inches="tight", facecolor="white")
    plt.close(fig)


def _cutoff(ax, x, color, label, style="-"):
    ax.axvline(x, color=color, linestyle=style, linewidth=2)
    ax.annotate(label, xy=(x, 1), xycoords=("data", "axes fraction"), xytext=(4, -4),
                textcoords="offset points", ha="left", va="top", fontsize=9, color=color, fontweight="bold")


def _qc_figure(log: list[Entry], figdir: Path) -> Figure | None:
    import matplotlib.pyplot as plt

    df = SESSION.qc_before_filter
    rec, filt = _last(log, "recommend_qc_thresholds"), _last(log, "filter_cells_and_genes")
    if df is None or not (rec and filt):
        return None
    default, applied = rec["summary"]["recommended"], filt["summary"]["applied"]
    mt, genes = df["pct_counts_mt"].to_numpy(), df["n_genes_by_counts"].to_numpy()
    n = len(df)
    lost_default = int((mt > default["max_pct_mt"]).sum())
    lost_chosen = int((mt > applied["max_pct_mt"]).sum())

    has_mito = bool(mt.max() > 0)
    with _style():
        if has_mito:
            fig, (a1, a2) = plt.subplots(1, 2, figsize=(10, 3.4))
            a1.hist(mt, bins=60, color=DATA, edgecolor="white", linewidth=0.5)
            a1.set(xlabel="Mitochondrial reads (%)", ylabel="Cells", title="Mitochondrial fraction")
            if applied["max_pct_mt"] != default["max_pct_mt"]:
                _cutoff(a1, default["max_pct_mt"], DEFAULT, f"default {_num(default['max_pct_mt'])}%\nremoves {_pct(lost_default, n)}", "--")
            _cutoff(a1, applied["max_pct_mt"], CHOSEN, f"chosen {_num(applied['max_pct_mt'])}%\nremoves {_pct(lost_chosen, n)}")
        else:
            fig, a2 = plt.subplots(figsize=(5.5, 3.4))

        a2.hist(genes, bins=60, color=DATA, edgecolor="white", linewidth=0.5)
        a2.set(xlabel="Genes detected per cell", ylabel="Cells", title="Genes per cell")
        lost_floor = int((genes < applied["min_genes"]).sum())
        _cutoff(a2, applied["min_genes"], CHOSEN, f"floor {_num(applied['min_genes'])}\nremoves {_pct(lost_floor, n)}")
        _save(fig, figdir / "qc_thresholds.png")

    if not has_mito:
        mito = "The data contains no mitochondrial reads (no mitochondrial genes), so the mitochondrial filter removes nothing."
    elif applied["max_pct_mt"] != default["max_pct_mt"]:
        mito = (f"The standard {_num(default['max_pct_mt'])}% mitochondrial cutoff (dashed) would remove "
                f"{_n(lost_default)} cells ({_pct(lost_default, n)}); the chosen {_num(applied['max_pct_mt'])}% cutoff "
                f"removes {_n(lost_chosen)} ({_pct(lost_chosen, n)}).")
    else:
        mito = (f"The standard {_num(default['max_pct_mt'])}% mitochondrial cutoff was kept and removes "
                f"{_n(lost_chosen)} cells ({_pct(lost_chosen, n)}).")
    median_mt = f", median {_num(np.median(mt))}% mitochondrial" if has_mito else ""
    caption = (f"Per-cell QC before filtering ({_n(n)} cells{median_mt}). {mito} Minimum genes per cell: "
               f"{_num(applied['min_genes'])}, which removes {_n(lost_floor)} cells (fewest observed: {_n(genes.min())}).")
    return Figure("qc_thresholds.png", "QC distributions with cutoffs", caption, (r"quality|\bqc\b", r"filter"))


def _doublet_figure(log: list[Entry], figdir: Path) -> Figure | None:
    import matplotlib.pyplot as plt

    scores = SESSION.doublet_scores
    det, dfilt = _last(log, "detect_doublets"), _last(log, "filter_doublets")
    if scores is None or not (det and dfilt):
        return None
    cands = det["summary"]["candidate_thresholds"]
    t = dfilt["args"]["threshold"]
    n = len(scores)
    flagged = int((scores >= t).sum())

    with _style():
        fig, ax = plt.subplots(figsize=(7, 3.4))
        ax.hist(scores, bins=80, color=DATA, edgecolor="white", linewidth=0.5)
        ax.set_yscale("log")
        ax.set(xlabel="Scrublet doublet score", ylabel="Cells (log scale)", title="Doublet scores")
        _cutoff(ax, t, CHOSEN, f"chosen {_num(t)}\nremoves {_pct(flagged, n)}")
        auto, auto_label = cands.get("scrublet_auto"), "Scrublet's automatic threshold"
        if auto is None and cands.get("scrublet_auto_per_batch"):
            vals = [v for v in cands["scrublet_auto_per_batch"].values() if v is not None]
            auto = float(np.mean(vals)) if vals else None
            auto_label = "The mean of Scrublet's per-batch automatic thresholds"
        if auto is not None and abs(auto - t) > 0.01:
            _cutoff(ax, auto, DEFAULT, f"Scrublet auto {_num(auto)}\nremoves {_pct(int((scores >= auto).sum()), n)}", "--")
        _save(fig, figdir / "doublet_scores.png")

    shape = "bimodal" if det["summary"]["is_bimodal"] else "not bimodal"
    rule = _nearest_rule(t, cands)
    caption = (f"Scrublet doublet scores for {_n(n)} cells; the distribution is {shape}. "
               f"Chosen threshold {_num(t)}" + (f" ({rule})" if rule else "") +
               f" flags {_n(flagged)} cells ({_pct(flagged, n)}).")
    if auto is not None and abs(auto - t) > 0.01:
        caption += f" {auto_label} (dashed, {_num(auto)}) would flag {_n(int((scores >= auto).sum()))}."
    return Figure("doublet_scores.png", "Doublet score distribution", caption, (r"doublet",))


def _condition_column() -> str | None:
    for settings in (SESSION.de_settings, (SESSION.composition or {}).get("settings")):
        if settings:
            return settings["contrast"][0]
    return None


def _umap_panel(adata, column: str, title: str, path: Path, size: float = 6.0) -> None:
    """One square UMAP coloured by `column`, legend underneath, for posters and slides.

    Not placed in the report (umap.png shows every colouring there). Cells are drawn in a
    fixed random order so no group is hidden under another, e.g. stim drawn over ctrl.
    """
    import matplotlib.pyplot as plt

    cats = adata.obs[column].astype("category")
    names = [str(n) for n in cats.cat.categories]
    colors = list(adata.uns.get(f"{column}_colors", []))
    if len(colors) != len(names):
        colors = [plt.cm.tab20(i % 20) for i in range(len(names))]
    order = np.random.default_rng(0).permutation(adata.n_obs)
    xy = adata.obsm["X_umap"][order]
    codes = cats.cat.codes.to_numpy()[order]

    longest = max(len(n) for n in names)
    ncol = 1 if longest > 30 else 2 if longest > 12 else 4 if longest > 3 else 6
    rows = -(-len(names) // ncol)
    legend_h = 0.22 * rows + 0.15  # inches
    title_h, pad = 0.45, 0.15
    side = size - title_h - legend_h - 2 * pad

    with _style():
        fig = plt.figure(figsize=(size, size))
        ax = fig.add_axes([(size - side) / 2 / size, (legend_h + pad) / size, side / size, side / size])
        ax.scatter(xy[:, 0], xy[:, 1], c=[colors[k] for k in codes], s=min(12.0, 30000 / adata.n_obs),
                   linewidths=0, rasterized=True)
        ax.set_axis_off()
        fig.text(0.5, 1 - (pad + title_h / 2) / size, title, ha="center", va="center",
                 fontsize=13, fontweight="bold", color=INK)
        handles = [plt.Line2D([], [], marker="o", linestyle="", markersize=7, color=col) for col in colors]
        fig.legend(handles, names, loc="lower center", bbox_to_anchor=(0.5, pad / size / 2), ncol=ncol,
                   fontsize=9, handletextpad=0.3, columnspacing=1.2, labelspacing=0.35)
        fig.savefig(path, dpi=300, facecolor="white")
        plt.close(fig)


def _umap_figure(adata, batch_key: str | None, figdir: Path) -> Figure | None:
    import matplotlib.pyplot as plt
    import scanpy as sc

    if "X_umap" not in adata.obsm:
        return None
    colors = [c for c in ("cell_type", "leiden") if c in adata.obs]
    titles = {"cell_type": "Cell type", "leiden": "Leiden cluster"}
    # For multi-batch data, colouring by batch shows whether integration mixed the batches
    # (good) or left them as separate islands (not integrated).
    if batch_key and batch_key in adata.obs:
        colors.append(batch_key)
        titles[batch_key] = f"Batch ({batch_key})"
    # When conditions were compared, colouring by condition shows whether cell types line up
    # across conditions, or whether a type splits (or a state exists) in one condition only.
    condition = _condition_column()
    if condition and condition in adata.obs and condition not in colors:
        colors.append(condition)
        titles[condition] = f"Condition ({condition})"
    with _style():
        sc.pl.umap(adata, color=colors, title=[titles[c] for c in colors], show=False, wspace=0.45,
                   frameon=False, legend_fontsize=8, ncols=2 if len(colors) > 3 else 4)
        _save(plt.gcf(), figdir / "umap.png")
        for c in colors:
            _umap_panel(adata, c, titles[c], figdir / f"umap_{c}.png")
    rep = {"X_scVI": "the scVI latent space", "X_pca": "PCA"}.get(SESSION.representation, SESSION.representation)
    names = [titles[c] if c == "leiden" else titles[c].lower() for c in colors]
    by = names[0] if len(names) == 1 else ", ".join(names[:-1]) + " and " + names[-1]
    caption = f"UMAP of {_n(adata.n_obs)} cells computed on {rep}, coloured by {by}."
    corrected = SESSION.scvi_batch_columns
    if corrected:
        caption += f" scVI corrected for {' × '.join(corrected)}."
    if batch_key in colors:
        caption += " Batches that overlap within each cell type indicate the integration worked."
    if condition in colors:
        caption += (" Conditions that overlap within each cell type mean the labels are comparable "
                    "between conditions; a region with only one condition may be a condition-specific state.")
    return Figure("umap.png", "UMAP", caption, (r"cluster", r"dimension|embedding|integration|umap"))


def _composition_figure(adata, figdir: Path) -> Figure | None:
    import matplotlib.pyplot as plt

    if "cell_type" not in adata.obs:
        return None
    counts = adata.obs["cell_type"].value_counts().sort_values()
    total = int(counts.sum())
    with _style():
        fig, ax = plt.subplots(figsize=(7, 0.32 * len(counts) + 0.9))
        ax.barh(counts.index.astype(str), counts.values, color=BAR, height=0.7)
        for y, v in enumerate(counts.values):
            ax.annotate(f"{_n(v)} ({_pct(v, total)})", xy=(v, y), xytext=(4, 0), textcoords="offset points",
                        va="center", fontsize=8, color=INK)
        ax.set(xlabel="Cells", title="Cell-type composition")
        ax.spines["left"].set_visible(False)
        ax.tick_params(axis="y", length=0)
        ax.set_xlim(0, counts.max() * 1.22)
        _save(fig, figdir / "composition.png")
    source = "CellTypist majority vote over Leiden clusters"
    if "cell_type_celltypist" in adata.obs:
        source += ", with clusters relabelled by the agent from their markers (see the decisions table)"
    caption = f"Cells per annotated type ({_n(total)} cells, {len(counts)} types; {source})."
    return Figure("composition.png", "Cell-type composition", caption, (r"composition", r"annot|cell.type"))


def _dotplot_figure(adata, groupby: str, figdir: Path) -> Figure | None:
    import matplotlib.pyplot as plt
    import scanpy as sc

    if groupby not in adata.obs or adata.obs[groupby].nunique() < 2:
        return None
    # Dedicated key so the cluster markers from identify_markers stay intact.
    key = f"dea_{groupby}"
    sc.tl.rank_genes_groups(adata, groupby, method="wilcoxon", key_added=key)
    what = "Leiden cluster" if groupby == "leiden" else "cell type"
    name = "marker_dotplot_clusters.png" if groupby == "leiden" else "marker_dotplot_celltype.png"
    with _style():
        sc.pl.rank_genes_groups_dotplot(adata, n_genes=5, key=key, groupby=groupby, standard_scale="var", show=False)
        _save(plt.gcf(), figdir / name)
    caption = (f"Top 5 marker genes per {what} (Wilcoxon rank-sum). Dot size: fraction of cells expressing; "
               "colour: mean expression scaled per gene.")
    return Figure(name, f"Marker genes per {what}", caption, (r"marker", r"annot|cell.type"))


def _slug(name: str) -> str:
    """Cell-type name as a placeholder key: 'CD14+ Monocytes' -> 'cd14_monocytes'."""
    return re.sub(r"[^a-z0-9]+", "_", name.lower()).strip("_")


REF_COLOR, TEST_COLOR = "#2a78d6", "#eb6834"
# Volcano plots: significant up red, significant down blue, the rest grey.
UP_COLOR, DOWN_COLOR, NS_COLOR = "#d62728", "#2a78d6", "#c8c8c8"


def _composition_change_figure(figdir: Path) -> Figure | None:
    import matplotlib.pyplot as plt

    comp = SESSION.composition
    if comp is None:
        return None
    props, table, st = comp["proportions"], comp["table"], comp["settings"]
    factor, test, ref = st["contrast"]
    order = table.sort_values(f"mean_prop_{ref}", ascending=False).index.tolist()
    by = {lvl: props.xs(lvl, level=factor) for lvl in (ref, test)}

    with _style():
        fig, ax = plt.subplots(figsize=(max(6, 0.75 * len(order) + 1.5), 4))
        for i, ct in enumerate(order):
            r, t = 100 * by[ref][ct], 100 * by[test][ct]
            if st["paired"]:
                shared = r.index.intersection(t.index)
                for sample in shared:
                    ax.plot([i - 0.18, i + 0.18], [r[sample], t[sample]], color="#c3c2b7", linewidth=0.8, zorder=1)
            ax.scatter(np.full(len(r), i - 0.18), r, s=22, color=REF_COLOR, zorder=2, label=ref if i == 0 else None)
            ax.scatter(np.full(len(t), i + 0.18), t, s=22, color=TEST_COLOR, zorder=2, label=test if i == 0 else None)
            padj = table.loc[ct, "padj"]
            if padj < 0.05:
                ax.annotate(f"padj {padj:.2g}", xy=(i, 1), xycoords=("data", "axes fraction"), ha="center",
                            va="top", fontsize=8, color=INK, fontweight="bold")
        # Symmetric log: log-like for the wide range of shares, but a sample with none of a
        # type (0%) still has a place on the axis.
        ax.set_yscale("symlog", linthresh=0.1)
        ax.set_ylim(bottom=0)
        ax.set_xticks(range(len(order)), order, rotation=40, ha="right")
        ax.set(ylabel="Cells in sample (%)", title=f"Cell-type proportions per {st['sample_key']}: {test} vs {ref}")
        ax.legend(loc="lower left", fontsize=8)
        _save(fig, figdir / "composition_change.png")

    n_sig = int((table["padj"] < 0.05).sum())
    design = f"lines join each {st['sample_key']}'s two samples" if st["paired"] else "samples are unpaired"
    caption = (f"Share of each cell type per sample, {ref} (blue) vs {test} (orange); {design}. "
               f"{st['test']} test with Benjamini-Hochberg correction: {n_sig} of {len(table)} cell types differ "
               "at padj < 0.05. Log scale above 0.1%, linear below, so samples with none of a type sit at 0.")
    return Figure("composition_change.png", "Cell-type proportions by condition", caption,
                  (r"abundance|proportion|composition (change|analysis|test|shift)", r"composition"))


def _slug(name: str) -> str:
    return re.sub(r"[^a-z0-9]+", "_", name.lower()).strip("_")


def _draw_volcano(ax, res: pd.DataFrame, title: str, point: float, label_size: float, title_size: float,
                  axis_size: float, n_labels: int = 3) -> None:
    res = res.dropna(subset=["padj"])
    y = -np.log10(res["padj"].clip(lower=1e-300))
    up = (res["padj"] < 0.05) & (res["log2FoldChange"] > 0)
    down = (res["padj"] < 0.05) & (res["log2FoldChange"] < 0)
    ax.scatter(res["log2FoldChange"][~(up | down)], y[~(up | down)], s=point, color=NS_COLOR, linewidths=0, rasterized=True)
    ax.scatter(res["log2FoldChange"][down], y[down], s=point * 1.3, color=DOWN_COLOR, linewidths=0, rasterized=True)
    ax.scatter(res["log2FoldChange"][up], y[up], s=point * 1.3, color=UP_COLOR, linewidths=0, rasterized=True)
    right_edge = res["log2FoldChange"].quantile(0.999)
    for k, gene in enumerate(res[up].sort_values("padj").index[:n_labels]):
        # Staggered offsets keep labels of near-identical points apart; a leader line ties each
        # label to its point. Labels near the right edge go to the left of their point.
        x = res.loc[gene, "log2FoldChange"]
        left = x > 0.7 * right_edge
        ax.annotate(gene, (x, y[gene]), fontsize=label_size, color=INK,
                    xytext=(-8 if left else 8, -1.3 * label_size * k), textcoords="offset points",
                    ha="right" if left else "left", va="center",
                    arrowprops={"arrowstyle": "-", "color": INK, "linewidth": 0.6, "shrinkA": 0, "shrinkB": 2})
    ax.set_title(f"{title}\n{int(up.sum())} up, {int(down.sum())} down", fontsize=title_size)
    ax.set_xlabel("log2 fold change", fontsize=axis_size)
    ax.set_ylabel("-log10 padj", fontsize=axis_size)


def _volcano_figure(figdir: Path) -> Figure | None:
    import matplotlib.pyplot as plt

    results, st = SESSION.de_results, SESSION.de_settings
    if not results or st is None:
        return None
    cts = list(results)
    factor, test, ref = st["contrast"]
    ncol = min(4, len(cts))
    nrow = int(np.ceil(len(cts) / ncol))
    with _style():
        fig, axes = plt.subplots(nrow, ncol, figsize=(3.2 * ncol, 3.0 * nrow), squeeze=False)
        for ax, ct in zip(axes.flat, cts):
            _draw_volcano(ax, results[ct], ct, point=3, label_size=7, title_size=9, axis_size=8)
        for ax in list(axes.flat)[len(cts):]:
            ax.axis("off")
        fig.tight_layout()
        _save(fig, figdir / "de_volcano.png")
        # One square volcano per cell type, for posters and slides; not placed in the report.
        for ct in cts:
            fig, ax = plt.subplots(figsize=(6, 6))
            _draw_volcano(ax, results[ct], f"{ct}: {test} vs {ref}", point=8, label_size=11, title_size=13,
                          axis_size=11, n_labels=5)
            fig.tight_layout()
            fig.savefig(figdir / f"volcano_{_slug(ct)}.png", dpi=300, facecolor="white")
            plt.close(fig)
    caption = (f"Pseudobulk differential expression, {test} vs {ref}, per cell type (PyDESeq2, design "
               f"`{st['design']}`, Wald test). Red: up in {test}; blue: down (padj < 0.05); grey: not significant. The three most "
               "significant up-regulated genes are labelled.")
    if st["skipped"]:
        caption += " Not tested (too few samples): " + ", ".join(st["skipped"]) + "."
    return Figure("de_volcano.png", "Volcano plots per cell type", caption, (r"differential|\bde\b|expression",))


# A canonical marker must pass all three in at least one cell type to be shown. Fold change
# and % expressing matter as much as padj: cell-level p-values treat cells as independent.
_CANON_PADJ, _CANON_LFC, _CANON_PCT = 0.05, 1.0, 0.25


def _checked_marker_support(adata, log: list[Entry]) -> tuple[list[str], pd.DataFrame] | None:
    """The genes the agent checked with check_markers, and each one's statistics in every
    final cell type that passes the enrichment filter. None if there is nothing to test."""
    import scanpy as sc

    checked = list(dict.fromkeys(g for e in log if e["tool"] == "check_markers" and "error" not in e["summary"]
                                 for g in e["args"]["genes"] if g in adata.var_names))
    if "cell_type" not in adata.obs or adata.obs["cell_type"].nunique() < 2:
        return None
    if not checked:
        return [], pd.DataFrame(columns=["group", "names", "logfoldchanges"])
    key = "canonical_cell_type"
    sc.tl.rank_genes_groups(adata, "cell_type", method="wilcoxon", key_added=key, pts=True, n_genes=adata.n_vars)
    stats = sc.get.rank_genes_groups_df(adata, group=None, key=key)
    stats = stats[stats["names"].isin(checked)]
    passing = stats[(stats["pvals_adj"] < _CANON_PADJ) & (stats["logfoldchanges"] > _CANON_LFC)
                    & (stats["pct_nz_group"] >= _CANON_PCT)]
    return checked, passing.assign(group=passing["group"].astype(str))


def unsupported_cell_types(adata, log: list[Entry]) -> list[str]:
    """Final cell types that no marker checked by the agent is enriched in. The agent brings
    the marker knowledge; this only checks that every label has some."""
    support = _checked_marker_support(adata, log)
    if support is None:
        return []
    _, passing = support
    types = sorted(adata.obs["cell_type"].astype(str).unique())
    return [ct for ct in types if ct not in set(passing["group"])]


def _canonical_dotplot_figure(adata, log: list[Entry], figdir: Path) -> Figure | None:
    """Dotplot of the canonical markers the agent checked (check_markers), kept only where
    they are enriched in at least one final cell type, grouped by the type they mark."""
    import matplotlib.pyplot as plt
    import scanpy as sc

    support = _checked_marker_support(adata, log)
    if support is None or support[1].empty:
        return None
    checked, passing = support
    # Each gene goes in the block of the type where it is most enriched.
    best = passing.sort_values("logfoldchanges", ascending=False).drop_duplicates("names")
    order = [str(c) for c in adata.obs["cell_type"].cat.categories] if hasattr(adata.obs["cell_type"], "cat") \
        else sorted(adata.obs["cell_type"].astype(str).unique())
    blocks = {ct: [g for g in checked if g in set(best.loc[best["group"] == ct, "names"])] for ct in order}
    blocks = {ct: genes for ct, genes in blocks.items() if genes}
    rows = list(blocks) + [ct for ct in order if ct not in blocks]
    genes = [g for block in blocks.values() for g in block]
    with _style():
        sc.pl.dotplot(adata, var_names=genes, groupby="cell_type", categories_order=rows,
                      standard_scale="var", show=False)
        _save(plt.gcf(), figdir / "marker_dotplot_canonical.png")
    kept = sum(len(g) for g in blocks.values())
    dropped = [g for g in checked if g not in set(best["names"])]
    caption = (f"Canonical markers checked by the agent before accepting or changing labels ({kept} of "
               f"{len(checked)} shown), ordered by the cell type each marks most, so the enriched dots run down the diagonal. A gene is shown if, in at least one "
               f"type, padj < {_CANON_PADJ}, log2FC > {_CANON_LFC:g} and it is expressed in at least "
               f"{100 * _CANON_PCT:.0f}% of cells. Dot size: fraction of cells expressing; colour: mean expression "
               "scaled per gene.")
    if dropped:
        caption += " Not enriched in any type: " + ", ".join(dropped) + "."
    return Figure("marker_dotplot_canonical.png", "Canonical marker genes per cell type", caption,
                  (r"annot|cell.type", r"marker"))


def draw_figures(adata, log: list[Entry], batch_key: str | None, figdir: Path) -> list[Figure]:
    import matplotlib

    matplotlib.use("Agg")
    figdir.mkdir(parents=True, exist_ok=True)
    figures = [
        _qc_figure(log, figdir),
        _doublet_figure(log, figdir),
        _umap_figure(adata, batch_key, figdir),
        _dotplot_figure(adata, "leiden", figdir),
        _canonical_dotplot_figure(adata, log, figdir),
        _composition_figure(adata, figdir),
        _dotplot_figure(adata, "cell_type", figdir),
        _composition_change_figure(figdir),
        _volcano_figure(figdir),
    ]
    return [f for f in figures if f]


def _figure_md(fig: Figure) -> str:
    return f"![{fig.alt}](figures/{fig.name})\n\n*{fig.caption}*"


_HEADING = re.compile(r"^(#{1,6})\s+(.*)$")


def place_figures(markdown: str, figures: list[Figure]) -> tuple[str, list[Figure]]:
    """Insert each figure at the end of the first section whose heading matches one of its
    patterns. Returns the new markdown and the figures no section matched."""
    lines = markdown.splitlines()
    headings = [(i, len(m.group(1)), m.group(2)) for i, line in enumerate(lines) if (m := _HEADING.match(line))]
    inserts: dict[int, list[Figure]] = defaultdict(list)
    unplaced = []
    for fig in figures:
        target = None
        for pattern in fig.sections:
            for k, (_, level, text) in enumerate(headings):
                if level > 1 and re.search(pattern, text, re.IGNORECASE):
                    target = next((j for j, lv, _ in headings[k + 1 :] if lv <= level), len(lines))
                    break
            if target is not None:
                break
        if target is None:
            unplaced.append(fig)
        else:
            inserts[target].append(fig)

    out: list[str] = []
    for i in range(len(lines) + 1):
        for fig in inserts.get(i, []):
            while out and not out[-1].strip():
                out.pop()
            out += ["", _figure_md(fig), ""]
        if i < len(lines):
            out.append(lines[i])
    return "\n".join(out), unplaced


def _insert_after_intro(markdown: str, block: str, skip_overview: bool = True) -> str:
    """Put `block` straight after the title, or after the opening overview section."""
    lines = markdown.strip("\n").splitlines()
    headings = [(i, len(m.group(1)), m.group(2)) for i, line in enumerate(lines) if (m := _HEADING.match(line))]
    at = 0
    if headings and headings[0][1] == 1:
        at = headings[0][0] + 1
        rest = headings[1:]
        if skip_overview and rest and re.search(r"overview|summary|introduction", rest[0][2], re.IGNORECASE):
            at = next((i for i, lv, _ in rest[1:] if lv <= rest[0][1]), len(lines))
    return "\n".join(lines[:at] + ["", block, ""] + lines[at:])


# --- methods -------------------------------------------------------------------


def _scvi_correction(summary: dict) -> str:
    cols = summary.get("batch_columns") or ([summary["batch_key"]] if summary.get("batch_key") else [])
    return f"correcting for {' × '.join(cols)}" if cols else "without batch correction"


def methods(log: list[Entry]) -> str:
    paras = []
    ids = _last(log, "check_gene_identifiers")
    qc = _last(log, "compute_qc")
    if ids and qc:
        paras.append(
            f"**Quality control.** Per-cell metrics were computed with scanpy `calculate_qc_metrics`; "
            f"mitochondrial genes were those prefixed `{ids['summary']['mito_prefix']}` "
            f"({qc['summary']['n_mito_genes_found']} found)."
        )
    filt = _last(log, "filter_cells_and_genes")
    if filt:
        a, s = filt["summary"]["applied"], filt["summary"]
        paras.append(
            f"**Filtering.** Cells with fewer than {_num(a['min_genes'])} detected genes or more than "
            f"{_num(a['max_pct_mt'])}% mitochondrial reads were removed, as were genes detected in fewer than "
            f"{_num(a['min_cells'])} cells ({_n(s['before']['n_cells'])} → {_n(s['after']['n_cells'])} cells, "
            f"{_n(s['before']['n_genes'])} → {_n(s['after']['n_genes'])} genes)."
        )
    det, dfilt = _last(log, "detect_doublets"), _last(log, "filter_doublets")
    if det and dfilt:
        per = f", run separately within each batch ('{det['summary']['batch_key']}')," if det["summary"]["batch_key"] else ""
        paras.append(
            f"**Doublets.** Doublet scores were computed with Scrublet (scanpy `pp.scrublet`){per} on raw counts; "
            f"cells scoring ≥ {_num(dfilt['args']['threshold'])} were removed "
            f"({_n(dfilt['summary']['removed'])} cells, {_num(dfilt['summary']['pct_removed'])}%)."
        )
    norm = _last(log, "normalize")
    if norm:
        s = norm["summary"]
        within = f", ranked within each batch ('{s['hvg_batch_key']}')" if s.get("hvg_batch_key") else ""
        paras.append(
            f"**Normalisation.** Raw counts were kept in `layers['counts']`; expression was scaled to "
            f"{_num(s['target_sum'])} counts per cell and log1p-transformed. The top {_n(s['n_top_genes_requested'])} "
            f"highly variable genes were flagged{within}."
        )
    scvi, pca = _last(log, "run_scvi"), _last(log, "run_pca")
    dr = max((e for e in (scvi, pca) if e), key=log.index, default=None)
    if dr and dr["tool"] == "run_scvi":
        s = dr["summary"]
        paras.append(
            f"**Embedding.** An scVI model ({s['n_latent']} latent dimensions, {s['epochs_trained']} epochs) was "
            f"trained on raw counts of {_n(s['n_hvgs_used'])} highly variable genes, "
            f"{_scvi_correction(s)}; its latent space was used for clustering, "
            "UMAP and annotation (raw counts were unchanged)."
        )
    elif dr:
        paras.append(f"**Embedding.** PCA ({dr['summary']['n_comps']} components) on the highly variable genes.")
    clus = _last(log, "cluster")
    if clus:
        paras.append(
            f"**Clustering.** A k-nearest-neighbour graph on that embedding was clustered with Leiden "
            f"(resolution {clus['summary']['resolution']:.1f}; {clus['summary']['n_clusters']} clusters) and "
            f"embedded with UMAP."
        )
    mk, ann = _last(log, "identify_markers"), _last(log, "annotate_celltypes")
    if mk or ann:
        text = "**Markers and annotation.** "
        if mk:
            text += "Marker genes per cluster were ranked with a Wilcoxon rank-sum test. "
        if ann:
            text += (f"Cell types were assigned with CellTypist (model `{ann['summary']['model']}`), using majority "
                     "voting over the Leiden clusters.")
        paras.append(text.strip())
    relabels = [e for e in log if e["tool"] == "relabel_clusters" and "error" not in e["summary"]]
    if relabels:
        changes = [c for e in relabels for c in e["summary"]["changes"]]
        paras.append(
            "**Label curation.** Where marker genes contradicted CellTypist, the agent relabelled whole clusters "
            f"({len(changes)} clusters; listed in the decisions table with the evidence). The original CellTypist "
            "labels are kept in `obs['cell_type_celltypist']`."
        )
    comp = _last(log, "compare_composition")
    if comp:
        a, sm = comp["args"], comp["summary"]
        paras.append(
            f"**Composition.** For each sample ('{a['sample_key']}' × condition), the share of cells of each type "
            f"('{a.get('celltype_key', 'cell_type')}') was computed and compared between {a['contrast'][1]} and "
            f"{a['contrast'][2]} with a {'paired ' if sm['paired'] else ''}{sm['test']} test; p-values were adjusted "
            "across cell types with the Benjamini-Hochberg method."
        )
    de = _last(log, "run_pseudobulk_de")
    if de:
        a, sm = de["args"], de["summary"]
        paras.append(
            f"**Differential expression.** Raw counts were summed per sample ('{a['sample_key']}' × condition) "
            f"within each cell type ('{a.get('celltype_key', 'cell_type')}'); samples with fewer than "
            f"{a.get('min_cells', 10)} cells were dropped, and genes were kept with at least 10 counts in at least as "
            f"many samples as the smaller condition. PyDESeq2 was fitted with design `{sm['design']}` and "
            f"{a['contrast'][1]} was compared with {a['contrast'][2]} using a Wald test; p-values were adjusted with "
            "Benjamini-Hochberg (padj < 0.05 called significant). Log2 fold changes are unshrunken."
        )
    if not paras:
        return ""

    packages = ["scanpy", "anndata", "numpy", "scipy"]
    if scvi:
        packages.append("scvi-tools")
    if ann:
        packages.append("celltypist")
    if comp:
        packages.append("statsmodels")
    if de:
        packages.append("pydeseq2")
    rows = [("Python", platform.python_version())] + [(p, _version(p)) for p in packages]
    rows.append(("LLM (analysis decisions and narrative)", config.MODEL))
    software = "\n".join(["| Software | Version |", "|---|---|"] + [f"| {a} | {b} |" for a, b in rows])

    return "\n\n".join([
        "## Methods",
        "*Generated from the tool log: these are the steps and parameters that actually ran.*",
        *paras,
        "### Software",
        software,
        "### Reproducibility",
        f"Random seed {config.SEED} for all stochastic steps. Every tool call, with the arguments the agent "
        "chose and the summary it read back, is in `tool_calls.jsonl`. `replay.py` re-runs those calls without "
        "the model, reproducing this analysis; running the agent again samples new choices from the model, so "
        "it can take different decisions.",
    ])


def _version(package: str) -> str:
    try:
        return metadata.version(package)
    except metadata.PackageNotFoundError:
        return "unknown"


# --- facts and tables the narrative cites (placeholders) ----------------------
#
# The agent never types a number into the report. It writes {{name}} for a fact below,
# {{celltype:NAME}} for one cell type's size, {{celltypes:A|B}} for several combined, and
# {{table:name}} for a code-built table; render() fills them in and rejects the report if
# any other number appears.

_QC_METRICS = {"genes": "n_genes_by_counts", "counts": "total_counts", "mito": "pct_counts_mt"}
_MARKERS_SHOWN = 5


def _p(value) -> str:
    return f"{_num(value)}%"


def facts(log: list[Entry], adata) -> dict[str, str]:
    f: dict[str, str] = {}
    if e := _last(log, "inspect_dataset"):
        s = e["summary"]
        f["input.n_cells"], f["input.n_genes"] = _n(s["n_cells"]), _n(s["n_genes"])
        if s.get("candidate_batch_key"):
            f["input.n_batches"], f["input.batch_key"] = str(s["n_batches"]), s["candidate_batch_key"]
    if e := _last(log, "compute_qc"):
        s = e["summary"]
        f["qc.n_mito_genes"] = str(s["n_mito_genes_found"])
        for short, col in _QC_METRICS.items():
            for q, v in s[col].items():
                f[f"qc.{short}.{q}"] = _p(v) if short == "mito" else _n(round(v))
    if e := _last(log, "recommend_qc_thresholds"):
        d, imp = e["summary"]["recommended"], e["summary"]["projected_impact"]
        f["default.max_pct_mt"], f["default.min_genes"], f["default.min_cells"] = _p(d["max_pct_mt"]), _n(d["min_genes"]), _n(d["min_cells"])
        f["default.mito_cells_removed"] = _n(imp["cells_removed_max_pct_mt"])
        f["default.mito_pct_removed"] = _pct(imp["cells_removed_max_pct_mt"], imp["cells_total"])
    if e := _last(log, "filter_cells_and_genes"):
        s = e["summary"]
        a = s["applied"]
        f["filter.max_pct_mt"], f["filter.min_genes"], f["filter.min_cells"] = _p(a["max_pct_mt"]), _n(a["min_genes"]), _n(a["min_cells"])
        f["filter.cells_before"], f["filter.cells_after"] = _n(s["before"]["n_cells"]), _n(s["after"]["n_cells"])
        f["filter.cells_removed"] = _n(s["removed"]["cells"])
        f["filter.pct_cells_removed"] = _pct(s["removed"]["cells"], s["before"]["n_cells"])
        f["filter.genes_before"], f["filter.genes_after"] = _n(s["before"]["n_genes"]), _n(s["after"]["n_genes"])
        f["filter.genes_removed"] = _n(s["removed"]["genes"])
    if e := _last(log, "detect_doublets"):
        s = e["summary"]
        c = s["candidate_thresholds"]
        f["doublet.distribution"] = "bimodal" if s["is_bimodal"] else "not bimodal"
        f["doublet.score_median"], f["doublet.score_max"] = _num(s["score_distribution"]["median"]), _num(s["score_distribution"]["max"])
        f["doublet.median_3mad"] = _num(c["median_3mad"])
        if c.get("bimodal_valley") is not None:
            f["doublet.valley"] = _num(c["bimodal_valley"])
        autos = [c["scrublet_auto"]] if c.get("scrublet_auto") is not None else [
            v for v in (c.get("scrublet_auto_per_batch") or {}).values() if v is not None]
        if autos:
            f["doublet.scrublet_auto"] = " / ".join(_num(v) for v in autos)
            if SESSION.doublet_scores is not None:
                flagged = int((SESSION.doublet_scores >= float(np.mean(autos))).sum())
                f["doublet.scrublet_auto_cells_flagged"] = _n(flagged)
    if e := _last(log, "filter_doublets"):
        s = e["summary"]
        f["doublet.threshold"] = _num(s["threshold"])
        if det := _last(log, "detect_doublets"):
            f["doublet.rule"] = _nearest_rule(s["threshold"], det["summary"]["candidate_thresholds"]) or "custom threshold"
        f["doublet.cells_before"], f["doublet.cells_after"] = _n(s["before_cells"]), _n(s["after_cells"])
        f["doublet.cells_removed"], f["doublet.pct_removed"] = _n(s["removed"]), _p(s["pct_removed"])
    if e := _last(log, "normalize"):
        s = e["summary"]
        f["norm.target_sum"], f["norm.n_hvgs"] = _num(s["target_sum"]), _n(s["n_hvgs_flagged"])
    if e := _last(log, "run_pca"):
        s = e["summary"]
        f["pca.n_comps"] = str(s["n_comps"])
        for k, v in enumerate(s["variance_ratio_top10"][:3], start=1):
            f[f"pca.pc{k}_variance"] = _p(round(100 * v, 1))
    if e := _last(log, "run_scvi"):
        s = e["summary"]
        f["scvi.n_latent"], f["scvi.n_hvgs"] = str(s["n_latent"]), _n(s["n_hvgs_used"])
        if s.get("epochs_trained"):
            f["scvi.epochs"] = str(s["epochs_trained"])
    if e := _last(log, "cluster"):
        s = e["summary"]
        sizes = s["cluster_sizes"].values()
        f["cluster.resolution"], f["cluster.n"] = f"{s['resolution']:.1f}", str(s["n_clusters"])
        f["cluster.smallest"], f["cluster.largest"] = _n(min(sizes)), _n(max(sizes))
    f["markers.n_shown"] = str(_MARKERS_SHOWN)
    if "cell_type" in adata.obs:
        f["celltype.n"] = str(adata.obs["cell_type"].nunique())
    if e := _last(log, "inspect_dataset"):
        for col, levels in e["summary"].get("obs_levels", {}).items():
            if col.isidentifier():
                f[f"input.n_{col}"] = str(len(levels))
    if SESSION.composition is not None:
        comp, st = SESSION.composition["table"], SESSION.composition["settings"]
        _, test, ref = st["contrast"]
        f["comp.test"] = ("paired " if st["paired"] else "") + st["test"]
        f["comp.n_significant"] = str(int((comp["padj"] < 0.05).sum()))
        f["comp.n_cell_types"] = str(len(comp))
        for ct, r in comp.iterrows():
            k = f"comp.{_slug(ct)}"
            f[f"{k}.{ref}"], f[f"{k}.{test}"] = _p(round(100 * r[f"mean_prop_{ref}"], 1)), _p(round(100 * r[f"mean_prop_{test}"], 1))
            f[f"{k}.log2_ratio"], f[f"{k}.padj"] = f"{r['log2_ratio']:.2f}", f"{r['padj']:.2g}"
            if r.get("n_samples_higher_in_test") is not None:
                # The value states its own meaning, so it can't be read the wrong way round.
                n = len(SESSION.composition["proportions"].xs(test, level=st["contrast"][0]))
                up = int(r["n_samples_higher_in_test"])
                f[f"{k}.direction"] = (f"higher in {test} in {up} of {n} {st['sample_key']}s, "
                                       f"lower or equal in {n - up}")
    if SESSION.de_settings is not None:
        st = SESSION.de_settings
        _, test, ref = st["contrast"]
        f["de.design"], f["de.contrast"] = f"`{st['design']}`", f"{test} vs {ref}"
        f["de.padj_threshold"], f["de.min_cells"] = "0.05", str(st["min_cells"])
        f["de.n_cell_types_tested"] = str(len(SESSION.de_results))
        f["de.skipped"] = ", ".join(st["skipped"]) or "none"
        for ct, res in SESSION.de_results.items():
            k = f"de.{_slug(ct)}"
            sig = res[res["padj"] < 0.05]
            f[f"{k}.genes_tested"] = _n(res["padj"].notna().sum())
            f[f"{k}.n_significant"] = _n(len(sig))
            f[f"{k}.n_up"], f[f"{k}.n_down"] = _n((sig["log2FoldChange"] > 0).sum()), _n((sig["log2FoldChange"] < 0).sum())
    if e := _last(log, "inspect_dataset"):
        total = e["summary"]["n_cells"]
        f["final.n_cells"], f["final.n_genes"] = _n(adata.n_obs), _n(adata.n_vars)
        f["final.cells_removed"] = _n(total - adata.n_obs)
        f["final.pct_removed"] = _pct(total - adata.n_obs, total)
    return f


def _celltypes(adata, names: list[str]) -> str | None:
    if "cell_type" not in adata.obs:
        return None
    counts = adata.obs["cell_type"].value_counts()
    if any(n not in counts.index for n in names):
        return None
    k = int(counts[names].sum())
    return f"{_n(k)} cells ({_pct(k, adata.n_obs)})"


def tables(log: list[Entry], adata) -> dict[str, str]:
    out: dict[str, str] = {}
    obs = adata.obs
    if "leiden" in obs and "cell_type" in obs:
        names = adata.uns["rank_genes_groups"]["names"] if "rank_genes_groups" in adata.uns else None
        majority = obs.groupby("leiden", observed=True)["cell_type"].agg(lambda s: s.value_counts().index[0])
        sizes = obs["leiden"].value_counts()
        curated = "cell_type_celltypist" in obs
        rows = ["| Cluster | Cells | Top marker genes | Cell type |" + (" CellTypist label |" if curated else ""),
                "|---|---|---|---|" + ("---|" if curated else "")]
        original = (obs.groupby("leiden", observed=True)["cell_type_celltypist"].agg(lambda s: s.value_counts().index[0])
                    if curated else None)
        for cl in sorted(majority.index, key=lambda c: int(c) if str(c).isdigit() else str(c)):
            markers = ", ".join(str(names[str(cl)][i]) for i in range(_MARKERS_SHOWN)) if names is not None else "—"
            label = f"**{majority[cl]}**" if curated and majority[cl] != original[cl] else majority[cl]
            rows.append(f"| {cl} | {_n(sizes[cl])} | {markers} | {label} |" + (f" {original[cl]} |" if curated else ""))
        out["clusters"] = "\n".join(rows)
    if "cell_type" in obs:
        counts = obs["cell_type"].value_counts()
        rows = ["| Cell type | Cells | Share |", "|---|---|---|"]
        rows += [f"| {name} | {_n(v)} | {_pct(v, adata.n_obs)} |" for name, v in counts.items()]
        rows.append(f"| **Total** | **{_n(adata.n_obs)}** | |")
        out["composition"] = "\n".join(rows)
    steps = []
    if e := _last(log, "inspect_dataset"):
        steps.append(("Input", e["summary"]["n_cells"], e["summary"]["n_genes"]))
    if e := _last(log, "filter_cells_and_genes"):
        s = e["summary"]
        steps.append((f"After QC filters (≤{_p(s['applied']['max_pct_mt'])} mito, ≥{_n(s['applied']['min_genes'])} genes/cell)",
                      s["after"]["n_cells"], s["after"]["n_genes"]))
    if e := _last(log, "filter_doublets"):
        steps.append((f"After doublet removal (score < {_num(e['summary']['threshold'])})", e["summary"]["after_cells"], None))
    if steps:
        rows = ["| Step | Cells | Genes |", "|---|---|---|"]
        genes = None
        for name, cells, g in steps:
            genes = g if g is not None else genes
            rows.append(f"| {name} | {_n(cells)} | {_n(genes) if genes is not None else '—'} |")
        out["steps"] = "\n".join(rows)
    out.update(_comparison_tables())
    return out


def _gene(arg: str) -> str | None:
    """{{gene:CELLTYPE:SYMBOL}} -> 'ISG15 (log2FC 7.66, padj 4.8e-73)'. CELLTYPE is the name or its slug."""
    ct, _, gene = arg.rpartition(":")
    ct = next((c for c in SESSION.de_results if ct.strip() in (c, _slug(c))), None)
    if ct is None:
        return None
    res = SESSION.de_results[ct]
    gene = gene.strip()
    if gene not in res.index or pd.isna(res.loc[gene, "padj"]):
        return None
    r = res.loc[gene]
    return f"{gene} (log2FC {r['log2FoldChange']:.2f}, padj {r['padj']:.2g})"


def _comparison_tables() -> dict[str, str]:
    out = {}
    if SESSION.composition is not None:
        comp, st = SESSION.composition["table"], SESSION.composition["settings"]
        _, test, ref = st["contrast"]
        rows = [f"| Cell type | Mean share, {ref} | Mean share, {test} | log2 ratio | padj |", "|---|---|---|---|---|"]
        rows += [f"| {ct} | {100 * r[f'mean_prop_{ref}']:.1f}% | {100 * r[f'mean_prop_{test}']:.1f}% | "
                 f"{r['log2_ratio']:.2f} | {r['padj']:.2g} |" for ct, r in comp.iterrows()]
        out["composition_test"] = "\n".join(rows)
    if SESSION.de_results:
        st = SESSION.de_settings
        rows = ["| Cell type | Samples (test / ref) | Genes tested | Up | Down | Top up-regulated genes |", "|---|---|---|---|---|---|"]
        _, test, ref = st["contrast"]
        for ct, res in SESSION.de_results.items():
            sig = res[res["padj"] < 0.05]
            up = sig[sig["log2FoldChange"] > 0].sort_values("padj").index[:5]
            meta = SESSION.de_results[ct].attrs.get("n_samples", {})
            samples = f"{meta.get(test, '?')} / {meta.get(ref, '?')}"
            rows.append(f"| {ct} | {samples} | {_n(res['padj'].notna().sum())} | {_n((sig['log2FoldChange'] > 0).sum())} | "
                        f"{_n((sig['log2FoldChange'] < 0).sum())} | {', '.join(up)} |")
        out["de_summary"] = "\n".join(rows)
    return out


REQUIRED_TABLES = ("clusters", "composition", "composition_test", "de_summary")
_PLACEHOLDER = re.compile(r"\{\{\s*([^{}]+?)\s*\}\}")
# A number standing on its own: not part of a gene or dataset name (CD14, MT-CO1, PBMC3k,
# PC1, 10x). Percent signs and thousands separators are included in the match.
_BARE_NUMBER = re.compile(r"(?<![\w\-.,+])\d+(?:[.,]\d+)*(?:\s?%)?(?![\w])")
_CLUSTER_REF = re.compile(r"\bclusters?\s+(\d+(?:\s*(?:,|and|or|&|/)\s*\d+)*)", re.IGNORECASE)
# Allowed forms that contain digits but are names, not values: the "median + 3×MAD" rule
# and gene shorthand such as S100A8/9 (S100A8 and S100A9).
_ALLOWED = re.compile(r"\b3\s*[×x*]\s*MAD\b|(?<=[A-Za-z])(\d+)(?:/\d+)+\b")
_LINE_PREFIX = re.compile(r"^\s*(?:#{1,6}\s+\d+(?:\.\d+)*\.?|\d+\.)\s")  # "## 2. QC", "1. item"


def _stray_numbers(markdown: str, cluster_ids: set[str]) -> tuple[list[str], list[str]]:
    """Numbers the model typed itself, and cluster references to clusters that don't exist."""
    stray, bad_clusters = [], []
    for line in markdown.splitlines():
        if line.lstrip().startswith("!["):
            continue
        text = _LINE_PREFIX.sub(" ", line)
        text = _PLACEHOLDER.sub(" ", text)
        text = _ALLOWED.sub(lambda m: m.group(1) or " ", text)

        def _cluster(m: re.Match) -> str:
            for cid in re.findall(r"\d+", m.group(1)):
                if cid not in cluster_ids:
                    bad_clusters.append(f"cluster {cid} does not exist (clusters: {', '.join(sorted(cluster_ids, key=int))})")
            return " "

        text = _CLUSTER_REF.sub(_cluster, text) if cluster_ids else text
        for m in _BARE_NUMBER.finditer(text):
            context = text[max(0, m.start() - 30) : m.end() + 15].strip()
            stray.append(f"'{m.group(0)}' in \"...{context}...\"")
    return list(dict.fromkeys(stray)), list(dict.fromkeys(bad_clusters))


def render(markdown: str, log: list[Entry], adata) -> tuple[str, list[str]]:
    """Fill every placeholder and check the narrative. Returns the rendered text and every
    problem found (empty if the report is clean)."""
    known, tabs = facts(log, adata), tables(log, adata)
    cluster_ids = set(adata.obs["leiden"].astype(str)) if "leiden" in adata.obs else set()
    problems: list[str] = []

    for m in re.finditer(r"^#{1,6}\s+(.*)$", markdown, re.MULTILINE):
        if re.search(r"\bmethods?\b", m.group(1), re.IGNORECASE):
            problems.append(f"remove the '{m.group(1).strip()}' section: Methods is generated from the tool log "
                            "and appended automatically. Explain analysis choices in the relevant results section.")

    stray, bad_clusters = _stray_numbers(markdown, cluster_ids)
    problems += [f"number typed directly, use a placeholder: {s}" for s in stray]
    problems += bad_clusters

    placed: set[str] = set()

    def _fill(m: re.Match) -> str:
        key = m.group(1)
        kind, _, arg = key.partition(":")
        value = None
        if kind == "table" and arg in tabs:
            placed.add(arg)
            return f"\n\n{tabs[arg]}\n\n"
        if not arg:
            value = known.get(key)
        elif kind == "celltype":
            value = _celltypes(adata, [arg.strip()])
        elif kind == "celltypes":
            value = _celltypes(adata, [a.strip() for a in arg.split("|")])
        elif kind == "gene":
            value = _gene(arg)
        if value is None:
            problems.append(f"unknown placeholder {{{{{key}}}}}")
            return f"⚠[unknown: {key}]"
        return value

    text = _PLACEHOLDER.sub(_fill, markdown)
    # "{{celltype:X}} cells" would read "12 cells (3.0%) cells".
    text = re.sub(r"(\d cells \([\d.]+%\))\s+cells\b", r"\1", text)
    problems += [f"required table not placed: {{{{table:{t}}}}}" for t in REQUIRED_TABLES if t in tabs and t not in placed]
    return text, problems


# --- assembly ------------------------------------------------------------------


def build_report(adata, narrative: str, batch_key: str | None, warnings: list[str] = ()) -> tuple[str, list[Figure]]:
    """Assemble the final report from the rendered narrative and the code-built parts.
    `warnings` are checks the narrative still fails; they are shown at the top."""
    log = read_log(SESSION.paths.tool_log)
    figures = draw_figures(adata, log, batch_key, SESSION.paths.figures)

    narrative = narrative.strip()
    if not narrative.startswith("# "):
        narrative = f"# Single-cell RNA-seq analysis: {SESSION.name}\n\n{narrative}"
    body, unplaced = place_figures(narrative, figures)
    if warnings:
        note = "> **⚠ This report failed automatic checks and needs review:**\n" + "\n".join(f"> - {w}" for w in warnings)
        body = _insert_after_intro(body, note, skip_overview=False)
    if table := decisions_table(log):
        body = _insert_after_intro(body, table)
    if summary := run_summary(log):
        body = _insert_after_intro(body, summary, skip_overview=False)
    parts = [body]
    if unplaced:
        parts.append("## Figures\n\n" + "\n\n".join(_figure_md(f) for f in unplaced))
    parts += [methods(log), "---", DISCLAIMER.format(model=config.MODEL)]
    text = "\n\n".join(p for p in parts if p)
    return re.sub(r"\n{3,}", "\n\n", text).rstrip() + "\n", figures
